"""remove_consent_buttons

Revision ID: bf798fcf46a6
Revises: 8e4ef63c6c7a
Create Date: 2026-01-16 22:34:00.154516

"""

from typing import Sequence, Union

from alembic import op  # type: ignore
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bf798fcf46a6"
down_revision: Union[str, Sequence[str], None] = "8e4ef63c6c7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("study_translations", "consent_accept")
    op.drop_column("study_translations", "consent_decline")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "study_translations",
        sa.Column("consent_decline", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "study_translations",
        sa.Column("consent_accept", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
