/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Optional human-readable explanation.
 */
export type AckResponseDetails = string | null;
