/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Generic acknowledgement: `{status: "...", details?: "..."}`.
 *
 * Used by endpoints that mutate state and only need to confirm success
 * (save_draft, update_progress, change_password, disable_totp, unlock_study).
 */
export interface AckResponse {
    /** Short status token, e.g. 'ok' or 'unlocked'. */
    status: string;
    /** Optional human-readable explanation. */
    details?: string | null;
}
