/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Body for POST /api/admin/users/{id}/set-email (superuser-only,
 * SMTP-optional direct email swap).
 */
export interface AdminSetEmailRequest {
    new_email: string;
}
