/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { AnalysisRunReadFactorNotes } from './analysisRunReadFactorNotes';
import type { AnalysisRunReadResult } from './analysisRunReadResult';
import type { ManualRotation } from './manualRotation';

/**
 * Full persisted run including the result payload.
 */
export interface AnalysisRunRead {
    id: number;
    ran_at: string;
    ran_by_user_id?: number | null;
    /** Email of the user who ran the analysis (joined from User; None if user deleted). */
    ran_by_email?: string | null;
    extraction_method: string;
    n_factors: number;
    rotation_method: string;
    flagging_mode: string;
    notes?: string | null;
    /** Per-factor interpretive narrative (Sneegas 2020). Keys are stringified 1-indexed factor numbers; values are free-text. */
    factor_notes?: AnalysisRunReadFactorNotes;
    /** The judgmental rotations applied to this run, in list order. Empty for 'varimax' or 'none' rotation. Persisted on the run for audit-trail traceability of which rotations produced the result (Brown 1980; Watts & Stenner 2012). */
    manual_rotations?: ManualRotation[];
    /** Number of bootstrap iterations B used by this run (Zabala & Pascual 2016). None = bootstrap was not run. */
    bootstrap_iterations?: number | null;
    /** Full AnalysisResult payload as it was returned at run time. */
    result: AnalysisRunReadResult;
}
