/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { BootstrapResult } from './bootstrapResult';

/**
 * Bootstrap stability output (Zabala & Pascual 2016). Set only when the request opted in via `bootstrap_iterations`.
 */
export type AnalysisResultBootstrap = BootstrapResult | null;
