/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Full AnalysisResult payload as it was returned at run time.
 */
export type AnalysisRunReadResult = { [key: string]: unknown };
