/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Optional: run a non-parametric bootstrap with B iterations to estimate SEs on z-scores (Zabala & Pascual 2016). None = skip.
 */
export type AnalysisRequestBootstrapIterations = number | null;
