/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Manual participant-to-factor assignments (participant_db_id → factor_number, 1-indexed)
 */
export type AnalysisRequestManualFlags = { [key: string]: number } | null;
