/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Number of bootstrap iterations B used by this run (Zabala & Pascual 2016). None = bootstrap was not run.
 */
export type AnalysisRunSummaryBootstrapIterations = number | null;
