/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { AnalysisRunPatchFactorNotesAnyOf } from './analysisRunPatchFactorNotesAnyOf';

/**
 * Per-factor narratives keyed by stringified 1-indexed factor number. The router validates that each key matches an actual factor of the run (1 ≤ int(k) ≤ run.n_factors); values are capped at 4000 chars per factor.
 */
export type AnalysisRunPatchFactorNotes = AnalysisRunPatchFactorNotesAnyOf | null;
