/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Exact count preview for a prospective bulk anonymisation.

Cheap (one COUNT query). No mutation, no audit. Filters out
already-anonymised participants so the count reflects what
bulk_anonymise_old_participants would actually anonymise — not the
larger raw `candidates` figure.
 */
export interface AnonymisePreviewResponse {
    cutoff: string;
    /** Completed, not-yet-anonymised participants whose submitted_at is strictly before cutoff. */
    candidates: number;
}
