/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

export interface AudioInventory {
    count: number;
    total_bytes: number;
    total_mb: number;
}
