/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for audio upload response.
 */
export interface AudioUploadResponse {
    recording_id: number;
    s3_key: string;
    file_size_bytes: number;
    presigned_url: string;
    message?: string;
}
