/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for reading audio recording metadata.
 */
export interface AudioRecordingRead {
    question_key: string;
    mime_type: string;
    file_size_bytes: number;
    duration_seconds?: number | null;
    id: number;
    s3_key: string;
    created_at: string;
    presigned_url?: string | null;
    url_expires_at?: string | null;
}
