/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * SE/CI for a single statement on a single factor.

Output of a non-parametric bootstrap of Q-sorts (Zabala & Pascual 2016):
the analysis is rerun B times on resampled Q-sort columns and the
distribution of z-scores per (statement, factor) yields a mean, an SE,
and a 95% empirical confidence interval.
 */
export interface BootstrapStatementStability {
    statement_id: number;
    /** 1-indexed factor number */
    factor: number;
    z_mean: number;
    z_se: number;
    /** 2.5th percentile of bootstrapped z-scores */
    ci_lower: number;
    /** 97.5th percentile of bootstrapped z-scores */
    ci_upper: number;
}
