/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { PartnerLogo } from './partnerLogo';

/**
 * Schema for study branding.
 */
export interface BrandingBase {
    logo_url?: string | null;
    accent_color?: string | null;
    primary_color?: string | null;
    partners?: PartnerLogo[];
}
