/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

export interface BulkAnonymiseResult {
    candidates: number;
    anonymised: number;
    skipped_already_anonymous: number;
}
