/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for reading a comment on a concourse item.
 */
export interface ConcourseItemCommentRead {
    id: number;
    item_id: number;
    user_id?: number | null;
    body: string;
    created_at: string;
    updated_at: string;
}
