/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { ConcourseItemStatus } from './concourseItemStatus';
import type { ConcourseItemVersionReadTranslationsSnapshotItem } from './concourseItemVersionReadTranslationsSnapshotItem';

/**
 * Schema for reading a concourse item version snapshot.
 */
export interface ConcourseItemVersionRead {
    id: number;
    item_id: number;
    version_number: number;
    code: string;
    status: ConcourseItemStatus;
    source?: string | null;
    translations_snapshot?: ConcourseItemVersionReadTranslationsSnapshotItem[];
    tag_ids_snapshot?: number[];
    change_comment?: string | null;
    changed_by?: number | null;
    changed_at: string;
}
