/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { ConcourseItemCreate } from './concourseItemCreate';

/**
 * Schema for bulk-creating concourse items.
 */
export interface ConcourseItemBulkCreate {
    /**
     * @minItems 1
     * @maxItems 500
     */
    items: ConcourseItemCreate[];
}
