/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for updating a concourse.
 */
export interface ConcourseUpdate {
    title?: string | null;
    description?: string | null;
}
