/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for reading a concourse (list view).
 */
export interface ConcourseRead {
    id: number;
    project_id: number;
    title: string;
    description?: string | null;
    item_count?: number;
    created_by?: number | null;
    created_at: string;
    updated_at: string;
}
