/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { ConcourseItemStatus } from './concourseItemStatus';
import type { ConcourseItemTranslationRead } from './concourseItemTranslationRead';
import type { ConcourseTagRead } from './concourseTagRead';

/**
 * Schema for reading a concourse item.
 */
export interface ConcourseItemRead {
    id: number;
    code: string;
    status: ConcourseItemStatus;
    source?: string | null;
    version: number;
    display_order: number;
    created_by?: number | null;
    created_at: string;
    updated_at: string;
    translations?: ConcourseItemTranslationRead[];
    tags?: ConcourseTagRead[];
    comment_count?: number;
}
