/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for creating a concourse.
 */
export interface ConcourseCreate {
    /**
     * @minLength 1
     * @maxLength 200
     */
    title: string;
    description?: string | null;
}
