/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for importing concourse items into a study as statements.
 */
export interface ConcourseImportToStudy {
    concourse_id: number;
    /**
     * @minItems 1
     * @maxItems 500
     */
    item_ids: number[];
    /** @maxLength 20 */
    code_prefix?: string;
    replace_existing?: boolean;
}
