/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { ConcourseItemRead } from './concourseItemRead';

/**
 * Schema for reading a concourse with items (detail view).
 */
export interface ConcourseDetailRead {
    id: number;
    project_id: number;
    title: string;
    description?: string | null;
    item_count?: number;
    created_by?: number | null;
    created_at: string;
    updated_at: string;
    items?: ConcourseItemRead[];
}
