/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { ConcourseItemStatus } from './concourseItemStatus';
import type { ConcourseItemTranslationCreate } from './concourseItemTranslationCreate';

/**
 * Schema for updating a concourse item. Version is required for optimistic locking.
 */
export interface ConcourseItemUpdate {
    /** Current version for optimistic locking */
    version: number;
    code?: string | null;
    source?: string | null;
    status?: ConcourseItemStatus | null;
    translations?: ConcourseItemTranslationCreate[] | null;
    tag_ids?: number[] | null;
    change_comment?: string | null;
}
