/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for reading a tag.
 */
export interface ConcourseTagRead {
    /**
     * @minLength 1
     * @maxLength 100
     */
    name: string;
    color?: string | null;
    id: number;
    project_id: number;
}
