/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for recording participant consent.
 */
export interface ConsentInput {
    study_slug: string;
    session_token: string;
    consent_hash?: string | null;
    /**
     * @maxLength 5
     * @pattern ^[a-z]{2}(-[A-Z]{2})?$
     */
    language_code: string;
}
