/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Study-level retention policy in months, used by the frontend to compute the default cutoff. NULL = use system default (12).
 */
export type DataInventoryDataRetentionMonths = number | null;
