/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Participant count by language_used
 */
export type DataInventoryLocales = { [key: string]: number };
