/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { AudioInventory } from './audioInventory';
import type { DataInventoryLocales } from './dataInventoryLocales';
import type { ParticipantBuckets } from './participantBuckets';
import type { TimelineSnapshot } from './timelineSnapshot';

/**
 * Per-study data inventory snapshot.
 */
export interface DataInventory {
    study_slug: string;
    generated_at: string;
    participants: ParticipantBuckets;
    audio: AudioInventory;
    timeline: TimelineSnapshot;
    /** Participant count by language_used */
    locales?: DataInventoryLocales;
    /** Study-level retention policy in months, used by the frontend to compute the default cutoff. NULL = use system default (12). */
    data_retention_months?: number | null;
}
