/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Enum for Q-sort grid distribution enforcement.

forced — activation requires sum(capacity) == len(statements); each column
    must hold exactly its declared capacity at submission
    (Brown 1980; Watts & Stenner 2012).
free — activation requires sum(capacity) >= len(statements) (the grid must
    fit every statement; declared capacities are an upper hint, columns
    may absorb overflow at sort time). Total submitted count must equal
    the Q-set size; per-column capacities are not enforced
    (Brown et al. 2015).
flexible — activation requires sum(capacity) == len(statements); total is
    enforced at submission; per-column capacities are soft hints
    (warnings only). Qualis-specific compromise.
 */
export type DistributionMode = (typeof DistributionMode)[keyof typeof DistributionMode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DistributionMode = {
    forced: 'forced',
    free: 'free',
    flexible: 'flexible',
} as const;
