/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Full response store state snapshot
 */
export type DraftSaveInputDraftResponses = { [key: string]: unknown };
