/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for submitting an email address (resend flows).
 */
export interface EmailRequest {
    email: string;
}
