/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

export type GetAudioUrlApiAudioRecordingIdUrlGetParams = {
    session_token: string;
};
