/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

export type GetStudyApiStudySlugGetParams = {
    lang?: string | null;
    /**
     * Participant session token for deterministic randomization
     */
    session_token?: string | null;
    /**
     * Recruitment link token
     */
    link_token?: string | null;
    /**
     * Study access password
     */
    password?: string | null;
};
