/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

export type GetTemplatesApiAdminMemoTemplatesGetParentType =
    (typeof GetTemplatesApiAdminMemoTemplatesGetParentType)[keyof typeof GetTemplatesApiAdminMemoTemplatesGetParentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetTemplatesApiAdminMemoTemplatesGetParentType = {
    concourse: 'concourse',
    study: 'study',
} as const;
