/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { GetTemplatesApiAdminMemoTemplatesGetParentType } from './getTemplatesApiAdminMemoTemplatesGetParentType';

export type GetTemplatesApiAdminMemoTemplatesGetParams = {
    parent_type: GetTemplatesApiAdminMemoTemplatesGetParentType;
};
