/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

export type GetTemplatesApiAdminMemoTemplatesGetParentType =
    (typeof GetTemplatesApiAdminMemoTemplatesGetParentType)[keyof typeof GetTemplatesApiAdminMemoTemplatesGetParentType];

export const GetTemplatesApiAdminMemoTemplatesGetParentType = {
    concourse: 'concourse',
    study: 'study',
} as const;
