/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema defining a column in the sorting grid.
 */
export interface GridColumn {
    /**
     * @minimum -10
     * @maximum 10
     */
    score: number;
    capacity: number;
}
