/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { LogEntryContext } from './logEntryContext';
import type { LogEntryLevel } from './logEntryLevel';

/**
 * Schema for frontend log entries.
 */
export interface LogEntry {
    level: LogEntryLevel;
    message: string;
    stack?: string | null;
    context?: LogEntryContext;
    url?: string | null;
    userAgent?: string | null;
}
