/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * A single judgmental rotation step.

Each step is a 2-D Givens rotation on the (factor_a, factor_b) column
pair of the loadings matrix by `angle_deg` degrees. Used by the
'judgmental' rotation method to align factors with substantively
meaningful positions (Brown 1980; Watts & Stenner 2012).
 */
export interface ManualRotation {
    /**
     * 1-indexed factor number to rotate.
     * @minimum 1
     */
    factor_a: number;
    /**
     * 1-indexed factor number to rotate around. Must differ from factor_a.
     * @minimum 1
     */
    factor_b: number;
    /**
     * Rotation angle in degrees, in [-180, 180].
     * @minimum -180
     * @maximum 180
     */
    angle_deg: number;
}
