/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

export interface MemoCommentUpdate {
    /**
     * @minLength 1
     * @maxLength 2000
     */
    body: string;
}
