/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

export type MemoEntryReadParentType =
    (typeof MemoEntryReadParentType)[keyof typeof MemoEntryReadParentType];

export const MemoEntryReadParentType = {
    concourse: 'concourse',
    study: 'study',
} as const;
