/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

export type MemoReadParentType = (typeof MemoReadParentType)[keyof typeof MemoReadParentType];

export const MemoReadParentType = {
    concourse: 'concourse',
    study: 'study',
} as const;
