/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { MemoCommentRead } from './memoCommentRead';
import type { MemoEntryReadParentType } from './memoEntryReadParentType';

export interface MemoEntryRead {
    id: number;
    parent_type: MemoEntryReadParentType;
    parent_id: number;
    title: string;
    body: string;
    position: number;
    created_at: string;
    updated_at: string;
    created_by: number | null;
    last_edited_by: number | null;
    comments: MemoCommentRead[];
}
