/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

export interface MemoEntryCreate {
    /**
     * @minLength 1
     * @maxLength 200
     */
    title: string;
    /** @maxLength 10000 */
    body?: string;
    position?: number | null;
}
