/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

export interface MemoEntryUpdate {
    title?: string | null;
    body?: string | null;
    position?: number | null;
}
