/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

export interface MemoCommentRead {
    id: number;
    entry_id: number;
    user_id: number | null;
    body: string;
    mentions: number[];
    resolved: boolean;
    resolved_at: string | null;
    resolved_by: number | null;
    deleted: boolean;
    created_at: string;
    updated_at: string;
}
