/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { MemoEntryRead } from './memoEntryRead';
import type { MemoReadParentType } from './memoReadParentType';

export interface MemoRead {
    parent_type: MemoReadParentType;
    parent_id: number;
    entries: MemoEntryRead[];
}
