/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

export type MemoEntryReadParentType =
    (typeof MemoEntryReadParentType)[keyof typeof MemoEntryReadParentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MemoEntryReadParentType = {
    concourse: 'concourse',
    study: 'study',
} as const;
