/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { MemoEntryCreatePosition } from './memoEntryCreatePosition';

export interface MemoEntryCreate {
    /**
     * @minLength 1
     * @maxLength 200
     */
    title: string;
    /** @maxLength 10000 */
    body?: string;
    position?: MemoEntryCreatePosition;
}
