/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { UserReadAdmin } from './userReadAdmin';

export interface PaginatedResponseUserReadAdmin {
    items: UserReadAdmin[];
    total: number;
    limit: number;
    offset: number;
}
