/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { StudyRead } from './studyRead';

export interface PaginatedResponseStudyRead {
    items: StudyRead[];
    total: number;
    limit: number;
    offset: number;
}
