/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { StudyListRead } from './studyListRead';

export interface PaginatedResponseStudyListRead {
    items: StudyListRead[];
    total: number;
    limit: number;
    offset: number;
}
