/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Enum for participant progress status.
 */
export type ParticipantStatus = (typeof ParticipantStatus)[keyof typeof ParticipantStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ParticipantStatus = {
    started: 'started',
    completed: 'completed',
} as const;
