/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { ParticipantExportResponseParticipant } from './participantExportResponseParticipant';
import type { ParticipantExportResponseStatementIdToIndex } from './participantExportResponseStatementIdToIndex';
import type { ParticipantExportResponseStudy } from './participantExportResponseStudy';

/**
 * Admin participant JSON export (GET /admin/.../participants/{id}/export/json).
 *
 * Open shape — the payload is `{study, participant, statement_id_to_index}`,
 * a single-participant slice of the full StudyDump. `extra='allow'` lets
 * additional dynamic keys survive round-tripping.
 */
export interface ParticipantExportResponse {
    study: ParticipantExportResponseStudy;
    participant: ParticipantExportResponseParticipant;
    statement_id_to_index: ParticipantExportResponseStatementIdToIndex;
    [key: string]: unknown;
}
