/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { ParticipantStatus } from './participantStatus';

/**
 * Schema for reading a participant.
 *
 * Security: the raw ``session_token`` is the participant's bearer credential
 * and is deliberately NOT exposed here — this schema is reachable by the
 * lowest (viewer) role via the study participant list. Only the truncated,
 * non-reversible ``code`` (session_token[:8]) is surfaced for display.
 * ``recruitment_token`` and ``user_agent`` are research metadata, not
 * credentials, and remain available.
 */
export interface ParticipantRead {
    id: number;
    study_id: number;
    code: string;
    language_used: string;
    status: ParticipantStatus;
    created_at: string;
    submitted_at: string | null;
    is_discarded: boolean;
    discard_reason: string | null;
    user_agent: string | null;
    last_step_reached?: number | null;
    last_step_reached_at?: string | null;
    recruitment_token?: string | null;
}
