/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { AudioRecordingRead } from './audioRecordingRead';
import type { ParticipantDetailReadPostsortAnswers } from './participantDetailReadPostsortAnswers';
import type { ParticipantDetailReadPresortAnswers } from './participantDetailReadPresortAnswers';
import type { ParticipantStatus } from './participantStatus';
import type { QSortEntryRead } from './qSortEntryRead';

/**
 * Schema for detailed participant view including responses.
 */
export interface ParticipantDetailRead {
    id: number;
    study_id: number;
    code: string;
    language_used: string;
    status: ParticipantStatus;
    created_at: string;
    submitted_at: string | null;
    is_discarded: boolean;
    discard_reason: string | null;
    user_agent: string | null;
    last_step_reached?: number | null;
    last_step_reached_at?: string | null;
    recruitment_token?: string | null;
    presort_answers: ParticipantDetailReadPresortAnswers;
    postsort_answers: ParticipantDetailReadPostsortAnswers;
    qsort_entries: QSortEntryRead[];
    audio_recordings?: AudioRecordingRead[];
}
