/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

export interface ParticipantBuckets {
    started: number;
    completed: number;
    discarded: number;
    anonymised: number;
    total: number;
}
