/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Audio recording with the owning participant's id, used in admin
 * multi-participant fetches (e.g., the per-factor voice panel in the
 * analysis page).
 */
export interface ParticipantAudioRecording {
    question_key: string;
    mime_type: string;
    file_size_bytes: number;
    duration_seconds?: number | null;
    id: number;
    s3_key: string;
    created_at: string;
    presigned_url?: string | null;
    url_expires_at?: string | null;
    participant_db_id: number;
}
