/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for a partner institution logo.
 */
export interface PartnerLogo {
    id: string;
    name: string;
    logo_url: string;
    url?: string | null;
}
