/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for changing password.
 */
export interface PasswordChange {
    current_password: string;
    /** @minLength 8 */
    new_password: string;
}
