/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for confirming identity with current password.
 */
export interface PasswordConfirm {
    current_password: string;
}
