/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { PostsortConfigQuestions } from './postsortConfigQuestions';

/**
 * Post-sort step: settings at the root, questions under ``questions``.
 *
 * Settings are open-ended (``extreme_columns``, ``prompts``, ``audio``,
 * consent switches, …) and kept as extra keys. The oldest studies stored
 * the question map at the root; that flat form is lifted here on every
 * write and was rewritten in stored rows by migration
 * ``normalise_postsort_config_shape``. The test is structural — every
 * value a dict with a ``type`` — because the settings keys are open-ended
 * and a settings-only config (the create dialog writes
 * ``{"email": {...}, "consent": {...}}``) must not be mistaken for
 * questions, which the export's old "no extreme_columns" rule did.
 */
export interface PostsortConfig {
    questions?: PostsortConfigQuestions;
    [key: string]: unknown;
}
