/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { PresortConfigFields } from './presortConfigFields';

/**
 * Pre-sort questionnaire: an on/off switch and a keyed field map.
 *
 * ``fields`` entries are open-ended JSON (type, label, options, …; the
 * canonical list of field types is ``PreSortFieldSchema`` in the
 * frontend). Unknown top-level keys are kept.
 *
 * Before the ``enabled`` switch existed the column held the field map
 * itself. That flat form is lifted into the wrapped one here, on every
 * write path, and migration ``normalise_presort_config_shape`` rewrote
 * the stored rows with the same rule — so readers take ``fields`` and
 * never sniff.
 */
export interface PresortConfig {
    enabled?: boolean;
    fields?: PresortConfigFields;
    [key: string]: unknown;
}
