/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { PreviewRangeRequestExtraction } from './previewRangeRequestExtraction';
import type { PreviewRangeRequestRotation } from './previewRangeRequestRotation';
import type { PreviewRangeRequestFlagging } from './previewRangeRequestFlagging';

/**
 * Request body for POST /analysis/preview-range.
 */
export interface PreviewRangeRequest {
    /**
     * Candidate k values, e.g. [2, 3, 4, 5, 6].
     * @minItems 1
     * @maxItems 8
     */
    n_factors_range: number[];
    extraction?: PreviewRangeRequestExtraction;
    rotation?: PreviewRangeRequestRotation;
    flagging?: PreviewRangeRequestFlagging;
}
