/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

export type PreviewRangeRequestRotation =
    (typeof PreviewRangeRequestRotation)[keyof typeof PreviewRangeRequestRotation];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PreviewRangeRequestRotation = {
    varimax: 'varimax',
    none: 'none',
    judgmental: 'judgmental',
} as const;
