/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

export type PreviewRangeRequestExtraction =
    (typeof PreviewRangeRequestExtraction)[keyof typeof PreviewRangeRequestExtraction];

export const PreviewRangeRequestExtraction = {
    pca: 'pca',
    centroid: 'centroid',
} as const;
