/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

export type PreviewRangeRequestExtraction =
    (typeof PreviewRangeRequestExtraction)[keyof typeof PreviewRangeRequestExtraction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PreviewRangeRequestExtraction = {
    pca: 'pca',
    centroid: 'centroid',
} as const;
