/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { PreviewRangeRow } from './previewRangeRow';

export interface PreviewRangeResponse {
    rows: PreviewRangeRow[];
}
