/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

export type PreviewRangeRequestFlagging =
    (typeof PreviewRangeRequestFlagging)[keyof typeof PreviewRangeRequestFlagging];

export const PreviewRangeRequestFlagging = {
    auto: 'auto',
    manual: 'manual',
} as const;
