/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

export type PreviewRangeRequestRotation =
    (typeof PreviewRangeRequestRotation)[keyof typeof PreviewRangeRequestRotation];

export const PreviewRangeRequestRotation = {
    varimax: 'varimax',
    none: 'none',
    judgmental: 'judgmental',
} as const;
