/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for a dynamic study process step.
 */
export interface ProcessStep {
    /** Unique ID for DND and tracking */
    id: string;
    /** @maxLength 100 */
    title: string;
    /** @maxLength 500 */
    description: string;
    /** Lucide icon name */
    icon: string;
    /** Hex color code or CSS variable */
    color?: string | null;
}
