/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { UserRead } from './userRead';
import type { ProjectRole } from './projectRole';

/**
 * Schema for reading project member details.
 */
export interface ProjectMemberRead {
    user_id: number;
    user: UserRead;
    role: ProjectRole;
    joined_at: string;
}
