/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for updating a project.
 */
export interface ProjectUpdate {
    title?: string | null;
    slug?: string | null;
}
