/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Enum for project roles.
 */
export type ProjectRole = (typeof ProjectRole)[keyof typeof ProjectRole];

export const ProjectRole = {
    owner: 'owner',
    member: 'member',
    viewer: 'viewer',
} as const;
