/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

export type PublicConfigEmailDelivery =
    (typeof PublicConfigEmailDelivery)[keyof typeof PublicConfigEmailDelivery];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PublicConfigEmailDelivery = {
    smtp: 'smtp',
    manual: 'manual',
} as const;
