/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

export type PublicConfigAudioStorage =
    (typeof PublicConfigAudioStorage)[keyof typeof PublicConfigAudioStorage];

export const PublicConfigAudioStorage = {
    available: 'available',
    unavailable: 'unavailable',
} as const;
