/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

export type PublicConfigEmailDelivery =
    (typeof PublicConfigEmailDelivery)[keyof typeof PublicConfigEmailDelivery];

export const PublicConfigEmailDelivery = {
    smtp: 'smtp',
    manual: 'manual',
} as const;
