/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

export type PublicConfigAudioStorage =
    (typeof PublicConfigAudioStorage)[keyof typeof PublicConfigAudioStorage];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PublicConfigAudioStorage = {
    available: 'available',
    unavailable: 'unavailable',
} as const;
