/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for individual statement placement during submission.
 */
export interface QSortEntryInput {
    statement_id: number;
    /**
     * @minimum -10
     * @maximum 10
     */
    grid_score: number;
    card_comment?: string | null;
}
