/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for reading individual statement placement.
 */
export interface QSortEntryRead {
    statement_id: number;
    grid_score: number;
    card_comment?: string | null;
    statement_code: string;
}
