/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Body for POST /api/admin/users/{id}/recovery-link.
 */
export const RecoveryLinkRequestValue = {
    kind: 'password_reset',
} as const;
export type RecoveryLinkRequest = typeof RecoveryLinkRequestValue;
