/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { RecruitmentLinkType } from './recruitmentLinkType';

/**
 * Schema for creating a recruitment link.
 */
export interface RecruitmentLinkCreate {
    name?: string | null;
    type?: RecruitmentLinkType;
    capacity?: number | null;
}
