/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { RecruitmentLinkType } from './recruitmentLinkType';

/**
 * Schema for reading a recruitment link.
 */
export interface RecruitmentLinkRead {
    name?: string | null;
    type?: RecruitmentLinkType;
    capacity?: number | null;
    id: number;
    study_id: number;
    token: string;
    usage_count: number;
    start_count: number;
    expires_at?: string | null;
    is_active?: boolean;
    created_at: string;
}
