/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { RecruitmentLinkCreateName } from './recruitmentLinkCreateName';
import type { RecruitmentLinkType } from './recruitmentLinkType';
import type { RecruitmentLinkCreateCapacity } from './recruitmentLinkCreateCapacity';

/**
 * Schema for creating a recruitment link.
 */
export interface RecruitmentLinkCreate {
    name?: RecruitmentLinkCreateName;
    type?: RecruitmentLinkType;
    capacity?: RecruitmentLinkCreateCapacity;
}
