/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Enum for types of recruitment links.
 */
export type RecruitmentLinkType = (typeof RecruitmentLinkType)[keyof typeof RecruitmentLinkType];

export const RecruitmentLinkType = {
    public: 'public',
    individual: 'individual',
    limited: 'limited',
} as const;
