/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { ResolvedStudyConfigResponseInstructions } from './resolvedStudyConfigResponseInstructions';
import type { ResolvedStudyConfigResponseLanguage } from './resolvedStudyConfigResponseLanguage';

/**
 * Public study config returned by GET /api/study/{slug}.

The runtime payload is rich and partially dynamic (translation-resolved
fields, optional pre/post-sort configs, ui_labels, branding) — too much
to enumerate exhaustively here without dragging the StudyConfig zod
schema's structure into Pydantic. We declare the well-known top-level
fields the frontend always reads and accept additional keys via
`extra='allow'`. This is enough for orval to emit a real interface
instead of an opaque dict.
 */
export interface ResolvedStudyConfigResponse {
    slug: string;
    title: string;
    description?: string;
    instructions?: ResolvedStudyConfigResponseInstructions;
    language?: ResolvedStudyConfigResponseLanguage;
    requires_password?: boolean;
    [key: string]: unknown;
}
