/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { StaleTranslation } from './staleTranslation';

/**
 * A statement whose concourse source has changed since import.
 */
export interface StaleStatementRead {
    statement_id: number;
    statement_code: string;
    source_concourse_item_id: number;
    source_deleted: boolean;
    current_translations: StaleTranslation[];
    concourse_translations: StaleTranslation[];
}
