/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * A single translation in a staleness diff.
 */
export interface StaleTranslation {
    language_code: string;
    text: string;
}
