/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { StatementClassificationSignificance } from './statementClassificationSignificance';

/**
 * Classification of a statement as distinguishing or consensus.
 */
export interface StatementClassification {
    statement_id: number;
    code: string;
    text: string;
    z_scores: (number | null)[];
    factor_arrays: number[];
    /** Pairwise significance levels, e.g. {'1-2': 'p<0.05', '1-3': 'p<0.01'} */
    significance?: StatementClassificationSignificance;
}
