/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { StatementTranslationRead } from './statementTranslationRead';

/**
 * Schema for reading a statement.
 */
export interface StatementRead {
    /** @maxLength 50 */
    code: string;
    id: number;
    display_order?: number;
    translations?: StatementTranslationRead[];
    source_concourse_item_id?: number | null;
    source_imported_at?: string | null;
}
