/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Z-scores and factor array values for a single statement.
 */
export interface StatementScore {
    statement_id: number;
    code: string;
    text: string;
    z_scores: (number | null)[];
    factor_arrays: number[];
}
