/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { StatementTranslationCreate } from './statementTranslationCreate';

/**
 * Schema for updating a statement text (by code).
 */
export interface StatementUpdate {
    /** @maxLength 50 */
    code: string;
    translations: StatementTranslationCreate[];
}
