/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Audio storage usage for a study (returned by GET /storage-usage).
 */
export interface StorageUsageResponse {
    total_bytes: number;
    total_mb: number;
    file_count: number;
    quota_mb: number;
    quota_bytes: number;
    usage_percent: number;
}
