/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { BrandingBase } from './brandingBase';
import type { DistributionMode } from './distributionMode';
import type { GridColumn } from './gridColumn';
import type { StatementCreate } from './statementCreate';
import type { StudyCreatePostsortConfig } from './studyCreatePostsortConfig';
import type { StudyCreatePresortConfig } from './studyCreatePresortConfig';
import type { StudyState } from './studyState';
import type { StudyTranslationCreate } from './studyTranslationCreate';

/**
 * Schema for creating a study.
 */
export interface StudyCreate {
    /**
     * @minLength 3
     * @maxLength 100
     * @pattern ^[a-z0-9-]+$
     */
    slug: string;
    state?: StudyState;
    grid_config: GridColumn[];
    presort_config: StudyCreatePresortConfig;
    postsort_config: StudyCreatePostsortConfig;
    branding?: BrandingBase | null;
    default_language?: string | null;
    show_statement_codes?: boolean;
    randomize_statement_order?: boolean;
    symmetry_lock?: boolean;
    /** Enable the rough-sort step (3-pile triage). When False, participants go directly from pre-sort to fine-sort. */
    rough_sort_enabled?: boolean;
    distribution_mode?: DistributionMode;
    start_date?: string | null;
    end_date?: string | null;
    data_retention_months?: number | null;
    translations: StudyTranslationCreate[];
    statements?: StatementCreate[];
}
