/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { StudyUpdateSlug } from './studyUpdateSlug';
import type { StudyUpdateState } from './studyUpdateState';
import type { StudyUpdateGridConfig } from './studyUpdateGridConfig';
import type { StudyUpdatePresortConfig } from './studyUpdatePresortConfig';
import type { StudyUpdatePostsortConfig } from './studyUpdatePostsortConfig';
import type { StudyUpdateBranding } from './studyUpdateBranding';
import type { StudyUpdateDefaultLanguage } from './studyUpdateDefaultLanguage';
import type { StudyUpdateShowStatementCodes } from './studyUpdateShowStatementCodes';
import type { StudyUpdateRandomizeStatementOrder } from './studyUpdateRandomizeStatementOrder';
import type { StudyUpdateSymmetryLock } from './studyUpdateSymmetryLock';
import type { StudyUpdateRoughSortEnabled } from './studyUpdateRoughSortEnabled';
import type { StudyUpdateDistributionMode } from './studyUpdateDistributionMode';
import type { StudyUpdateTranslations } from './studyUpdateTranslations';
import type { StudyUpdateStatements } from './studyUpdateStatements';
import type { StudyUpdateAccessPassword } from './studyUpdateAccessPassword';
import type { StudyUpdateStartDate } from './studyUpdateStartDate';
import type { StudyUpdateEndDate } from './studyUpdateEndDate';
import type { StudyUpdateDataRetentionMonths } from './studyUpdateDataRetentionMonths';
import type { StudyUpdateLastUpdatedAt } from './studyUpdateLastUpdatedAt';

/**
 * Schema for updating a study.
 */
export interface StudyUpdate {
    slug?: StudyUpdateSlug;
    state?: StudyUpdateState;
    grid_config?: StudyUpdateGridConfig;
    presort_config?: StudyUpdatePresortConfig;
    postsort_config?: StudyUpdatePostsortConfig;
    branding?: StudyUpdateBranding;
    default_language?: StudyUpdateDefaultLanguage;
    show_statement_codes?: StudyUpdateShowStatementCodes;
    randomize_statement_order?: StudyUpdateRandomizeStatementOrder;
    symmetry_lock?: StudyUpdateSymmetryLock;
    rough_sort_enabled?: StudyUpdateRoughSortEnabled;
    distribution_mode?: StudyUpdateDistributionMode;
    translations?: StudyUpdateTranslations;
    statements?: StudyUpdateStatements;
    access_password?: StudyUpdateAccessPassword;
    start_date?: StudyUpdateStartDate;
    end_date?: StudyUpdateEndDate;
    data_retention_months?: StudyUpdateDataRetentionMonths;
    last_updated_at?: StudyUpdateLastUpdatedAt;
}
