/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { StudyImportRequestConfig } from './studyImportRequestConfig';

export interface StudyImportRequest {
    config: StudyImportRequestConfig;
    new_slug: string;
}
