/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { BrandingBase } from './brandingBase';
import type { DistributionMode } from './distributionMode';
import type { GridColumn } from './gridColumn';
import type { PostsortConfig } from './postsortConfig';
import type { PresortConfig } from './presortConfig';
import type { ProjectBrief } from './projectBrief';
import type { RecruitmentLinkRead } from './recruitmentLinkRead';
import type { StatementRead } from './statementRead';
import type { StudyState } from './studyState';
import type { StudyTranslationRead } from './studyTranslationRead';

/**
 * Schema for reading a study.
 */
export interface StudyRead {
    /**
     * @minLength 3
     * @maxLength 100
     * @pattern ^[a-z0-9-]+$
     */
    slug: string;
    state?: StudyState;
    grid_config: GridColumn[];
    presort_config: PresortConfig;
    postsort_config: PostsortConfig;
    branding?: BrandingBase | null;
    default_language?: string | null;
    show_statement_codes?: boolean;
    randomize_statement_order?: boolean;
    symmetry_lock?: boolean;
    /** Enable the rough-sort step (3-pile triage). When False, participants go directly from pre-sort to fine-sort. */
    rough_sort_enabled?: boolean;
    distribution_mode?: DistributionMode;
    start_date?: string | null;
    end_date?: string | null;
    data_retention_months?: number | null;
    id: number;
    project_id: number;
    project?: ProjectBrief | null;
    created_at: string;
    updated_at: string;
    translations?: StudyTranslationRead[];
    statements?: StatementRead[];
    recruitment_links?: RecruitmentLinkRead[];
    requires_password?: boolean;
    participant_count?: number;
}
