/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { BrandingBase } from './brandingBase';
import type { DistributionMode } from './distributionMode';
import type { GridColumn } from './gridColumn';
import type { StatementUpdate } from './statementUpdate';
import type { StudyState } from './studyState';
import type { StudyTranslationCreate } from './studyTranslationCreate';
import type { StudyUpdatePostsortConfig } from './studyUpdatePostsortConfig';
import type { StudyUpdatePresortConfig } from './studyUpdatePresortConfig';

/**
 * Schema for updating a study.
 */
export interface StudyUpdate {
    slug?: string | null;
    state?: StudyState | null;
    grid_config?: GridColumn[] | null;
    presort_config?: StudyUpdatePresortConfig;
    postsort_config?: StudyUpdatePostsortConfig;
    branding?: BrandingBase | null;
    default_language?: string | null;
    show_statement_codes?: boolean | null;
    randomize_statement_order?: boolean | null;
    symmetry_lock?: boolean | null;
    rough_sort_enabled?: boolean | null;
    distribution_mode?: DistributionMode | null;
    translations?: StudyTranslationCreate[] | null;
    statements?: StatementUpdate[] | null;
    access_password?: string | null;
    start_date?: string | null;
    end_date?: string | null;
    data_retention_months?: number | null;
    last_updated_at?: string | null;
}
