/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { ProcessStep } from './processStep';
import type { StudyTranslationCreateStepHelp } from './studyTranslationCreateStepHelp';
import type { StudyTranslationCreateUiLabels } from './studyTranslationCreateUiLabels';

/**
 * Schema for creating a study translation.
 */
export interface StudyTranslationCreate {
    /**
     * @maxLength 5
     * @pattern ^[a-z]{2}(-[A-Z]{2})?$
     */
    language_code: string;
    /** @maxLength 200 */
    title: string;
    /** @maxLength 5000 */
    description?: string;
    instructions?: string | null;
    subtitle?: string | null;
    objective?: string | null;
    condition_of_instruction?: string | null;
    pre_instruction?: string | null;
    consent_title?: string | null;
    consent_description?: string | null;
    ui_labels?: StudyTranslationCreateUiLabels;
    process_steps?: ProcessStep[];
    methodology_tips?: string[];
    step_help?: StudyTranslationCreateStepHelp;
}
