/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { StudyState } from './studyState';
import type { GridColumn } from './gridColumn';
import type { StudyListReadPresortConfig } from './studyListReadPresortConfig';
import type { StudyListReadPostsortConfig } from './studyListReadPostsortConfig';
import type { StudyListReadBranding } from './studyListReadBranding';
import type { StudyListReadDefaultLanguage } from './studyListReadDefaultLanguage';
import type { DistributionMode } from './distributionMode';
import type { StudyListReadStartDate } from './studyListReadStartDate';
import type { StudyListReadEndDate } from './studyListReadEndDate';
import type { StudyListReadDataRetentionMonths } from './studyListReadDataRetentionMonths';
import type { StudyListReadProject } from './studyListReadProject';
import type { StudyTranslationRead } from './studyTranslationRead';

/**
 * Lighter Study read for the list endpoint.

Omits the heavy ``statements`` and ``recruitment_links`` collections (and
their nested translation rows) that the study list never renders. Declaring
them on ``StudyRead`` forces SQLAlchemy to materialise them at serialization
time — thousands of rows for a 50-study page — even though only the title /
language badge / counts are shown (audit H1). ``translations`` is kept (the
list shows a per-study language badge).
 */
export interface StudyListRead {
    /**
     * @minLength 3
     * @maxLength 100
     * @pattern ^[a-z0-9-]+$
     */
    slug: string;
    state?: StudyState;
    grid_config: GridColumn[];
    presort_config: StudyListReadPresortConfig;
    postsort_config: StudyListReadPostsortConfig;
    branding?: StudyListReadBranding;
    default_language?: StudyListReadDefaultLanguage;
    show_statement_codes?: boolean;
    randomize_statement_order?: boolean;
    symmetry_lock?: boolean;
    /** Enable the rough-sort step (3-pile triage). When False, participants go directly from pre-sort to fine-sort. */
    rough_sort_enabled?: boolean;
    distribution_mode?: DistributionMode;
    start_date?: StudyListReadStartDate;
    end_date?: StudyListReadEndDate;
    data_retention_months?: StudyListReadDataRetentionMonths;
    id: number;
    project_id: number;
    project?: StudyListReadProject;
    created_at: string;
    updated_at: string;
    translations?: StudyTranslationRead[];
    requires_password?: boolean;
    participant_count?: number;
}
