/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Enum for study lifecycle states.
 */
export type StudyState = (typeof StudyState)[keyof typeof StudyState];

export const StudyState = {
    draft: 'draft',
    active: 'active',
    paused: 'paused',
    closed: 'closed',
    archived: 'archived',
} as const;
