/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { BrandingBase } from './brandingBase';
import type { DistributionMode } from './distributionMode';
import type { GridColumn } from './gridColumn';
import type { PostsortConfig } from './postsortConfig';
import type { PresortConfig } from './presortConfig';
import type { ProjectBrief } from './projectBrief';
import type { StudyState } from './studyState';
import type { StudyTranslationRead } from './studyTranslationRead';

/**
 * Lighter Study read for the list endpoint.
 *
 * Omits the heavy ``statements`` and ``recruitment_links`` collections (and
 * their nested translation rows) that the study list never renders. Declaring
 * them on ``StudyRead`` forces SQLAlchemy to materialise them at serialization
 * time — thousands of rows for a 50-study page — even though only the title /
 * language badge / counts are shown (audit H1). ``translations`` is kept (the
 * list shows a per-study language badge).
 */
export interface StudyListRead {
    /**
     * @minLength 3
     * @maxLength 100
     * @pattern ^[a-z0-9-]+$
     */
    slug: string;
    state?: StudyState;
    grid_config: GridColumn[];
    presort_config: PresortConfig;
    postsort_config: PostsortConfig;
    branding?: BrandingBase | null;
    default_language?: string | null;
    show_statement_codes?: boolean;
    randomize_statement_order?: boolean;
    symmetry_lock?: boolean;
    /** Enable the rough-sort step (3-pile triage). When False, participants go directly from pre-sort to fine-sort. */
    rough_sort_enabled?: boolean;
    distribution_mode?: DistributionMode;
    start_date?: string | null;
    end_date?: string | null;
    data_retention_months?: number | null;
    id: number;
    project_id: number;
    project?: ProjectBrief | null;
    created_at: string;
    updated_at: string;
    translations?: StudyTranslationRead[];
    requires_password?: boolean;
    participant_count?: number;
}
