/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { StudyStatsReadDeviceBreakdown } from './studyStatsReadDeviceBreakdown';

/**
 * Schema for study statistics.
 */
export interface StudyStatsRead {
    started_count: number;
    completed_count: number;
    completion_rate: number;
    median_duration_seconds: number | null;
    device_breakdown: StudyStatsReadDeviceBreakdown;
}
