/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { SubmissionInputStatus } from './submissionInputStatus';
import type { SubmissionInputPresortAnswers } from './submissionInputPresortAnswers';
import type { QSortEntryInput } from './qSortEntryInput';
import type { SubmissionInputPostsortAnswers } from './submissionInputPostsortAnswers';
import type { SubmissionInputLinkToken } from './submissionInputLinkToken';

/**
 * Schema for the full study submission/completion.
 */
export interface SubmissionInput {
    study_slug: string;
    session_token: string;
    /**
     * @maxLength 5
     * @pattern ^[a-z]{2}(-[A-Z]{2})?$
     */
    language_used: string;
    status?: SubmissionInputStatus;
    presort_answers?: SubmissionInputPresortAnswers;
    qsort: QSortEntryInput[];
    postsort_answers?: SubmissionInputPostsortAnswers;
    link_token?: SubmissionInputLinkToken;
}
