/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { ParticipantStatus } from './participantStatus';
import type { QSortEntryInput } from './qSortEntryInput';
import type { SubmissionInputPostsortAnswers } from './submissionInputPostsortAnswers';
import type { SubmissionInputPresortAnswers } from './submissionInputPresortAnswers';

/**
 * Schema for the full study submission/completion.
 */
export interface SubmissionInput {
    study_slug: string;
    session_token: string;
    /**
     * @maxLength 5
     * @pattern ^[a-z]{2}(-[A-Z]{2})?$
     */
    language_used: string;
    status?: ParticipantStatus | null;
    presort_answers?: SubmissionInputPresortAnswers;
    qsort: QSortEntryInput[];
    postsort_answers?: SubmissionInputPostsortAnswers;
    link_token?: string | null;
}
