/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Result of a participant Q-sort submission (POST /api/submit).
 *
 * Returned by the submit endpoint after StudyService.process_submission
 * completes. `already_submitted` is only present when re-submitting a
 * completed participation. `extra='allow'` covers any future additions.
 */
export interface SubmissionResultResponse {
    status: string;
    confirmation_code: string;
    id: number;
    already_submitted?: boolean | null;
    [key: string]: unknown;
}
