/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

export interface TestMemberData {
    email: string;
    project_slug: string;
    role: string;
}
