/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { TestUserData } from './testUserData';
import type { TestProjectData } from './testProjectData';

export interface TestSeedData {
    user: TestUserData;
    project: TestProjectData;
}
