/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

export interface TimelineSnapshot {
    first_submission_at: string | null;
    last_submission_at: string | null;
    last_anonymisation_at: string | null;
    /** Completed participants whose submitted_at is more than 1 year ago */
    completed_older_than_1y: number;
    /** Completed participants whose submitted_at is more than 2 years ago */
    completed_older_than_2y: number;
}
