/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for returning an access token or 2FA requirement.
 *
 * `requires_2fa=True` (with no access token) signals the frontend to
 * prompt for the authenticator-app code; a successful response carries
 * the access token instead.
 */
export interface Token {
    access_token?: string | null;
    token_type?: string | null;
    requires_2fa?: boolean;
    temp_token?: string | null;
}
