/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Result of enabling 2FA: status token + backup recovery codes.
 */
export interface TOTPEnableResponse {
    status: string;
    /** One-time backup codes to store offline. */
    backup_codes?: string[];
}
