/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { TwoFAEnableRequestToken } from './twoFAEnableRequestToken';

/**
 * Body of POST /me/2fa/enable.

`token` is the 6-digit TOTP code from the authenticator app, verified
against the secret seeded by /me/2fa/setup.
 */
export interface TwoFAEnableRequest {
    token?: TwoFAEnableRequestToken;
}
