/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Extended user read schema for superuser-only admin endpoints.
 *
 * Carries audit fields that we do NOT expose on the public /api/me path:
 * superusers see them so they can audit account hygiene
 * (last login, password age, email verification status).
 */
export interface UserReadAdmin {
    email: string;
    full_name?: string | null;
    id: number;
    is_active: boolean;
    is_superuser: boolean;
    is_totp_enabled: boolean;
    pending_email?: string | null;
    email_verified_at?: string | null;
    password_changed_at: string;
    last_login_at?: string | null;
}
