/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for reading user details.
 */
export interface UserRead {
    email: string;
    full_name?: string | null;
    id: number;
    is_active: boolean;
    is_superuser: boolean;
    is_totp_enabled: boolean;
    pending_email?: string | null;
}
