/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for updating user profile.
 */
export interface UserUpdate {
    email?: string | null;
    full_name?: string | null;
}
