/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * PATCH payload for /api/admin/users/{id}.
 *
 * Each field is optional so superusers can change one flag at a time
 * (e.g. demote without touching activation status). Email and password
 * are deliberately absent: email goes through the user-driven
 * /me email-change flow; password goes through force-password-reset.
 */
export interface UserAdminUpdate {
    is_active?: boolean | null;
    is_superuser?: boolean | null;
    full_name?: string | null;
}
