/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for creating a new user.
 */
export interface UserCreate {
    email: string;
    full_name?: string | null;
    /** @minLength 8 */
    password: string;
    is_active?: boolean;
    is_superuser?: boolean;
    invitation_token?: string | null;
}
