/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

export interface ValidationSummary {
    title: string;
    languages: string[];
    statement_count: number;
    grid_range: string;
    has_presort: boolean;
    has_postsort: boolean;
}
