/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { ValidationSummary } from './validationSummary';

export interface ValidationResult {
    valid: boolean;
    errors: string[];
    warnings: string[];
    summary?: ValidationSummary | null;
}
