/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Researcher annotation, e.g. 'final analysis used in submission'.
 */
export type AnalysisRunPatchNotes = string | null;
