/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Email of the user who ran the analysis (joined from User; None if user deleted).
 */
export type AnalysisRunSummaryRanByEmail = string | null;
