/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { ParticipantLoading } from './participantLoading';
import type { StatementScore } from './statementScore';
import type { StatementClassification } from './statementClassification';
import type { FactorCharacteristic } from './factorCharacteristic';
import type { ManualRotation } from './manualRotation';
import type { AnalysisResultBootstrap } from './analysisResultBootstrap';

/**
 * Complete result of a Q-method factor analysis.
 */
export interface AnalysisResult {
    n_participants: number;
    n_statements: number;
    n_factors: number;
    extraction: string;
    rotation: string;
    eigenvalues: number[];
    total_variance_explained: number;
    /** Unrotated loadings: n_participants x n_factors */
    loadings: number[][];
    /** Rotated loadings: n_participants x n_factors */
    rotated_loadings: number[][];
    /** Flagging matrix: n_participants x n_factors */
    flags: boolean[][];
    participants: ParticipantLoading[];
    statement_scores: StatementScore[];
    distinguishing: StatementClassification[];
    consensus: StatementClassification[];
    factor_characteristics: FactorCharacteristic[];
    /** Between-factor correlation matrix: n_factors x n_factors */
    correlation_matrix: number[][];
    /** The judgmental rotations applied to produce this result, in list order. Empty for 'varimax' or 'none' rotation. */
    manual_rotations?: ManualRotation[];
    /** Bootstrap stability output (Zabala & Pascual 2016). Set only when the request opted in via `bootstrap_iterations`. */
    bootstrap?: AnalysisResultBootstrap;
    /** Non-fatal warnings raised while computing this result, e.g. centroid extraction that did not fully converge (F-06-010). Empty when the analysis ran cleanly. Surfaced to the researcher above the results. */
    warnings?: string[];
}
