/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { AnalysisRequestManualFlagsAnyOf } from './analysisRequestManualFlagsAnyOf';

/**
 * Manual participant-to-factor assignments (participant_db_id → factor_number, 1-indexed)
 */
export type AnalysisRequestManualFlags = AnalysisRequestManualFlagsAnyOf | null;
