/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { AnalysisRunPatchNotes } from './analysisRunPatchNotes';

/**
 * Partial update for a persisted run. Only `notes` is editable.
 */
export interface AnalysisRunPatch {
    /** Researcher annotation, e.g. 'final analysis used in submission'. */
    notes?: AnalysisRunPatchNotes;
}
