/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { AnalysisRequestManualFlags } from './analysisRequestManualFlags';

/**
 * Schema for requesting a Q-method factor analysis.
 */
export interface AnalysisRequest {
    /** Factor extraction method: 'pca' or 'centroid' */
    extraction?: string;
    /**
     * Number of factors to extract
     * @minimum 1
     * @maximum 20
     */
    n_factors?: number;
    /** Rotation method: 'varimax' or 'none' */
    rotation?: string;
    /** Flagging method: 'auto' or 'manual' */
    flagging?: string;
    /** Manual participant-to-factor assignments (participant_db_id → factor_number, 1-indexed) */
    manual_flags?: AnalysisRequestManualFlags;
}
