/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { ManualRotation } from './manualRotation';

/**
 * Sequence of judgmental rotations to apply (only used when rotation='judgmental'). Each entry rotates the (factor_a, factor_b) pair by angle_deg degrees; rotations are applied in list order.
 */
export type AnalysisRequestManualRotations = ManualRotation[] | null;
