/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { AnalysisRunSummaryRanByUserId } from './analysisRunSummaryRanByUserId';
import type { AnalysisRunSummaryRanByEmail } from './analysisRunSummaryRanByEmail';
import type { AnalysisRunSummaryNotes } from './analysisRunSummaryNotes';

/**
 * Lightweight summary of a persisted analysis run, used in list views.
 */
export interface AnalysisRunSummary {
    id: number;
    ran_at: string;
    ran_by_user_id?: AnalysisRunSummaryRanByUserId;
    /** Email of the user who ran the analysis (joined from User; None if user deleted). */
    ran_by_email?: AnalysisRunSummaryRanByEmail;
    extraction_method: string;
    n_factors: number;
    rotation_method: string;
    flagging_mode: string;
    notes?: AnalysisRunSummaryNotes;
}
