/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { AnalysisRunReadRanByUserId } from './analysisRunReadRanByUserId';
import type { AnalysisRunReadRanByEmail } from './analysisRunReadRanByEmail';
import type { AnalysisRunReadNotes } from './analysisRunReadNotes';
import type { AnalysisRunReadResult } from './analysisRunReadResult';

/**
 * Full persisted run including the result payload.
 */
export interface AnalysisRunRead {
    id: number;
    ran_at: string;
    ran_by_user_id?: AnalysisRunReadRanByUserId;
    /** Email of the user who ran the analysis (joined from User; None if user deleted). */
    ran_by_email?: AnalysisRunReadRanByEmail;
    extraction_method: string;
    n_factors: number;
    rotation_method: string;
    flagging_mode: string;
    notes?: AnalysisRunReadNotes;
    /** Full AnalysisResult payload as it was returned at run time. */
    result: AnalysisRunReadResult;
}
