/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { AudioRecordingReadDurationSeconds } from './audioRecordingReadDurationSeconds';
import type { AudioRecordingReadPresignedUrl } from './audioRecordingReadPresignedUrl';

/**
 * Schema for reading audio recording metadata.
 */
export interface AudioRecordingRead {
    question_key: string;
    mime_type: string;
    file_size_bytes: number;
    duration_seconds?: AudioRecordingReadDurationSeconds;
    id: number;
    s3_key: string;
    created_at: string;
    presigned_url?: AudioRecordingReadPresignedUrl;
}
