/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { BodyLoginForAccessTokenApiTokenPostGrantType } from './bodyLoginForAccessTokenApiTokenPostGrantType';
import type { BodyLoginForAccessTokenApiTokenPostClientId } from './bodyLoginForAccessTokenApiTokenPostClientId';
import type { BodyLoginForAccessTokenApiTokenPostClientSecret } from './bodyLoginForAccessTokenApiTokenPostClientSecret';

export interface BodyLoginForAccessTokenApiTokenPost {
    grant_type?: BodyLoginForAccessTokenApiTokenPostGrantType;
    username: string;
    password: string;
    scope?: string;
    client_id?: BodyLoginForAccessTokenApiTokenPostClientId;
    client_secret?: BodyLoginForAccessTokenApiTokenPostClientSecret;
}
