/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { BodyUploadAudioApiAudioUploadPostDurationSeconds } from './bodyUploadAudioApiAudioUploadPostDurationSeconds';

export interface BodyUploadAudioApiAudioUploadPost {
    file: Blob;
    session_token: string;
    question_key: string;
    duration_seconds?: BodyUploadAudioApiAudioUploadPostDurationSeconds;
}
