/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { BootstrapStatementStability } from './bootstrapStatementStability';

/**
 * Bootstrap stability output (Zabala & Pascual 2016).

Returned alongside the regular analysis result when the analyst opted in
by setting ``bootstrap_iterations`` on the request.
 */
export interface BootstrapResult {
    /** Number of bootstrap iterations B that were attempted. */
    n_iterations: number;
    /** Number of iterations that produced a usable factor solution. Pathological resamples (degenerate correlation matrix, etc.) are skipped. */
    n_converged: number;
    /** One entry per (statement, factor) pair with non-empty samples. */
    statements: BootstrapStatementStability[];
    /** Per-factor mean SE of z-scores, length = n_factors. Powers the 'Mean SE (z)' column in the factor characteristics table. */
    factor_mean_se: number[];
}
