/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { BrandingBaseLogoUrl } from './brandingBaseLogoUrl';
import type { BrandingBaseAccentColor } from './brandingBaseAccentColor';
import type { BrandingBasePrimaryColor } from './brandingBasePrimaryColor';
import type { PartnerLogo } from './partnerLogo';

/**
 * Schema for study branding.
 */
export interface BrandingBase {
    logo_url?: BrandingBaseLogoUrl;
    accent_color?: BrandingBaseAccentColor;
    primary_color?: BrandingBasePrimaryColor;
    partners?: PartnerLogo[];
}
