/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { BrandingBaseLogoUrl } from './brandingBaseLogoUrl';
import type { BrandingBaseAccentColor } from './brandingBaseAccentColor';
import type { PartnerLogo } from './partnerLogo';

/**
 * Schema for study branding.
 */
export interface BrandingBase {
    logo_url?: BrandingBaseLogoUrl;
    accent_color?: BrandingBaseAccentColor;
    partners?: PartnerLogo[];
}
