/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Bulk anonymise completed participants whose submitted_at is older
than the given cutoff.
 */
export interface BulkAnonymiseRequest {
    /** ISO timestamp; only completed participants with submitted_at strictly before this are anonymised. */
    submitted_before: string;
}
