/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for importing items from a text block (one statement per line).
 */
export interface ConcourseItemBulkImport {
    /**
     * @minLength 1
     * @maxLength 100000
     */
    text_block: string;
    /**
     * @maxLength 5
     * @pattern ^[a-z]{2}(-[A-Z]{2})?$
     */
    language_code: string;
    /** @maxLength 20 */
    code_prefix?: string;
}
