/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { ConcourseCreateDescription } from './concourseCreateDescription';

/**
 * Schema for creating a concourse.
 */
export interface ConcourseCreate {
    /**
     * @minLength 1
     * @maxLength 200
     */
    title: string;
    description?: ConcourseCreateDescription;
}
