/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { ConcourseDetailReadDescription } from './concourseDetailReadDescription';
import type { ConcourseDetailReadCreatedBy } from './concourseDetailReadCreatedBy';
import type { ConcourseItemRead } from './concourseItemRead';

/**
 * Schema for reading a concourse with items (detail view).
 */
export interface ConcourseDetailRead {
    id: number;
    project_id: number;
    title: string;
    description?: ConcourseDetailReadDescription;
    item_count?: number;
    created_by?: ConcourseDetailReadCreatedBy;
    created_at: string;
    updated_at: string;
    items?: ConcourseItemRead[];
}
