/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { ConcourseItemCreateSource } from './concourseItemCreateSource';
import type { ConcourseItemStatus } from './concourseItemStatus';
import type { ConcourseItemTranslationCreate } from './concourseItemTranslationCreate';

/**
 * Schema for creating a concourse item.
 */
export interface ConcourseItemCreate {
    /** @maxLength 50 */
    code: string;
    source?: ConcourseItemCreateSource;
    status?: ConcourseItemStatus;
    /** @minItems 1 */
    translations: ConcourseItemTranslationCreate[];
    tag_ids?: number[];
}
