/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { ConcourseTagReadColor } from './concourseTagReadColor';

/**
 * Schema for reading a tag.
 */
export interface ConcourseTagRead {
    /**
     * @minLength 1
     * @maxLength 100
     */
    name: string;
    color?: ConcourseTagReadColor;
    id: number;
    workspace_id: number;
}
