/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { ConcourseReadDescription } from './concourseReadDescription';
import type { ConcourseReadCreatedBy } from './concourseReadCreatedBy';

/**
 * Schema for reading a concourse (list view).
 */
export interface ConcourseRead {
    id: number;
    workspace_id: number;
    title: string;
    description?: ConcourseReadDescription;
    item_count?: number;
    created_by?: ConcourseReadCreatedBy;
    created_at: string;
    updated_at: string;
}
