/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for creating a comment on a concourse item.
 */
export interface ConcourseItemCommentCreate {
    /**
     * @minLength 1
     * @maxLength 2000
     */
    body: string;
}
