/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { ConcourseItemUpdateCode } from './concourseItemUpdateCode';
import type { ConcourseItemUpdateSource } from './concourseItemUpdateSource';
import type { ConcourseItemUpdateStatus } from './concourseItemUpdateStatus';
import type { ConcourseItemUpdateTranslations } from './concourseItemUpdateTranslations';
import type { ConcourseItemUpdateTagIds } from './concourseItemUpdateTagIds';
import type { ConcourseItemUpdateChangeComment } from './concourseItemUpdateChangeComment';

/**
 * Schema for updating a concourse item. Version is required for optimistic locking.
 */
export interface ConcourseItemUpdate {
    /** Current version for optimistic locking */
    version: number;
    code?: ConcourseItemUpdateCode;
    source?: ConcourseItemUpdateSource;
    status?: ConcourseItemUpdateStatus;
    translations?: ConcourseItemUpdateTranslations;
    tag_ids?: ConcourseItemUpdateTagIds;
    change_comment?: ConcourseItemUpdateChangeComment;
}
