/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { ConcourseUpdateTitle } from './concourseUpdateTitle';
import type { ConcourseUpdateDescription } from './concourseUpdateDescription';

/**
 * Schema for updating a concourse.
 */
export interface ConcourseUpdate {
    title?: ConcourseUpdateTitle;
    description?: ConcourseUpdateDescription;
}
