/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { ConcourseTagCreateColor } from './concourseTagCreateColor';

/**
 * Schema for creating a workspace-scoped tag.
 */
export interface ConcourseTagCreate {
    /**
     * @minLength 1
     * @maxLength 100
     */
    name: string;
    color?: ConcourseTagCreateColor;
}
