/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { ConcourseItemStatus } from './concourseItemStatus';

export type ConcourseItemUpdateStatus = ConcourseItemStatus | null;
