/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for importing concourse items into a study as statements.
 */
export interface ConcourseImportToStudy {
    concourse_id: number;
    /** @minItems 1 */
    item_ids: number[];
    /** @maxLength 20 */
    code_prefix?: string;
    replace_existing?: boolean;
}
