/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for reading a concourse item translation.
 */
export interface ConcourseItemTranslationRead {
    /**
     * @maxLength 5
     * @pattern ^[a-z]{2}(-[A-Z]{2})?$
     */
    language_code: string;
    /** @maxLength 1000 */
    text: string;
    id: number;
    item_id: number;
}
