/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { ConsentInputConsentHash } from './consentInputConsentHash';

/**
 * Schema for recording participant consent.
 */
export interface ConsentInput {
  study_slug: string;
  session_token: string;
  consent_hash?: ConsentInputConsentHash;
  /**
   * @maxLength 5
   * @pattern ^[a-z]{2}(-[A-Z]{2})?$
   */
  language_code: string;
}
