/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for the consent endpoint response.
 */
export interface ConsentResponse {
    status: string;
    resume_code: string;
}
