/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { ParticipantBuckets } from './participantBuckets';
import type { AudioInventory } from './audioInventory';
import type { TimelineSnapshot } from './timelineSnapshot';
import type { DataInventoryLocales } from './dataInventoryLocales';

/**
 * Per-study data inventory snapshot.
 */
export interface DataInventory {
    study_slug: string;
    generated_at: string;
    participants: ParticipantBuckets;
    audio: AudioInventory;
    timeline: TimelineSnapshot;
    /** Participant count by language_used */
    locales?: DataInventoryLocales;
}
