/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { DraftSaveInputDraftResponses } from './draftSaveInputDraftResponses';

/**
 * Schema for saving participant draft responses.
 */
export interface DraftSaveInput {
    session_token: string;
    /** Full response store state snapshot */
    draft_responses: DraftSaveInputDraftResponses;
}
