/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Full response store state snapshot
 */
export type DraftSaveInputDraftResponses = { [key: string]: unknown };
