/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Eigenvalues for scree plot (pre-analysis).
 */
export interface EigenvalueResult {
    eigenvalues: number[];
    /** Suggested number of factors (Kaiser criterion: eigenvalue > 1) */
    suggested_n_factors: number;
}
