/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Statistical characteristics for a single factor.
 */
export interface FactorCharacteristic {
    /** 1-indexed factor number */
    factor: number;
    eigenvalue: number;
    variance_explained: number;
    cumulative_variance: number;
    n_flagged: number;
    /** Average reliability coefficient */
    avg_rel_coef: number;
    composite_reliability: number;
    /** Standard error of factor scores */
    se_factor_scores: number;
}
