/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */

export type GetStudyApiStudySlugGetParams = {
    /**
     * @maxLength 5
     * @pattern ^[a-z]{2}(-[A-Z]{2})?$
     */
    lang?: string;
    /**
     * Participant session token for deterministic randomization
     */
    session_token?: string | null;
    /**
     * Recruitment link token
     */
    link_token?: string | null;
    /**
     * Study access password
     */
    password?: string | null;
};
