/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema defining a column in the sorting grid.
 */
export interface GridColumn {
  score: number;
  capacity: number;
}
