/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { StudyRole } from './studyRole';

/**
 * Schema for creating a study invitation.
 */
export interface InvitationCreate {
    email: string;
    role?: StudyRole;
}
