/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for returning a generated invitation link.
 */
export interface InvitationLink {
    invite_url: string;
    token: string;
}
