/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

export type LogEntryLevel = (typeof LogEntryLevel)[keyof typeof LogEntryLevel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LogEntryLevel = {
    error: 'error',
    warn: 'warn',
    info: 'info',
    debug: 'debug',
} as const;
