/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { LogEntryLevel } from './logEntryLevel';
import type { LogEntryStack } from './logEntryStack';
import type { LogEntryContext } from './logEntryContext';
import type { LogEntryUrl } from './logEntryUrl';
import type { LogEntryUserAgent } from './logEntryUserAgent';

/**
 * Schema for frontend log entries.
 */
export interface LogEntry {
    level: LogEntryLevel;
    message: string;
    stack?: LogEntryStack;
    context?: LogEntryContext;
    url?: LogEntryUrl;
    userAgent?: LogEntryUserAgent;
}
