/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { LogEntryContextAnyOf } from './logEntryContextAnyOf';

export type LogEntryContext = LogEntryContextAnyOf | null;
