/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { MemoEntryUpdateTitle } from './memoEntryUpdateTitle';
import type { MemoEntryUpdateBody } from './memoEntryUpdateBody';
import type { MemoEntryUpdatePosition } from './memoEntryUpdatePosition';

export interface MemoEntryUpdate {
    title?: MemoEntryUpdateTitle;
    body?: MemoEntryUpdateBody;
    position?: MemoEntryUpdatePosition;
}
