/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { UserRead } from './userRead';

export interface PaginatedResponseUserRead {
    items: UserRead[];
    total: number;
    limit: number;
    offset: number;
}
