/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { ConcourseRead } from './concourseRead';

export interface PaginatedResponseConcourseRead {
    items: ConcourseRead[];
    total: number;
    limit: number;
    offset: number;
}
