/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectMemberRead } from './projectMemberRead';

export interface PaginatedResponseProjectMemberRead {
    items: ProjectMemberRead[];
    total: number;
    limit: number;
    offset: number;
}
