/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { ParticipantStatus } from './participantStatus';
import type { ParticipantReadSubmittedAt } from './participantReadSubmittedAt';
import type { ParticipantReadDiscardReason } from './participantReadDiscardReason';
import type { ParticipantReadUserAgent } from './participantReadUserAgent';

/**
 * Schema for reading a participant.
 */
export interface ParticipantRead {
    id: number;
    study_id: number;
    session_token: string;
    language_used: string;
    status: ParticipantStatus;
    created_at: string;
    submitted_at: ParticipantReadSubmittedAt;
    is_discarded: boolean;
    discard_reason: ParticipantReadDiscardReason;
    user_agent: ParticipantReadUserAgent;
}
