/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { ParticipantStatus } from './participantStatus';
import type { ParticipantDetailReadSubmittedAt } from './participantDetailReadSubmittedAt';
import type { ParticipantDetailReadDiscardReason } from './participantDetailReadDiscardReason';
import type { ParticipantDetailReadUserAgent } from './participantDetailReadUserAgent';
import type { ParticipantDetailReadPresortAnswers } from './participantDetailReadPresortAnswers';
import type { ParticipantDetailReadPostsortAnswers } from './participantDetailReadPostsortAnswers';
import type { QSortEntryInput } from './qSortEntryInput';

/**
 * Schema for detailed participant view including responses.
 */
export interface ParticipantDetailRead {
  id: number;
  study_id: number;
  session_token: string;
  language_used: string;
  status: ParticipantStatus;
  created_at: string;
  submitted_at: ParticipantDetailReadSubmittedAt;
  is_discarded: boolean;
  discard_reason: ParticipantDetailReadDiscardReason;
  user_agent: ParticipantDetailReadUserAgent;
  presort_answers: ParticipantDetailReadPresortAnswers;
  postsort_answers: ParticipantDetailReadPostsortAnswers;
  qsort_entries: QSortEntryInput[];
}
