/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { ParticipantAudioRecordingDurationSeconds } from './participantAudioRecordingDurationSeconds';
import type { ParticipantAudioRecordingPresignedUrl } from './participantAudioRecordingPresignedUrl';
import type { ParticipantAudioRecordingUrlExpiresAt } from './participantAudioRecordingUrlExpiresAt';

/**
 * Audio recording with the owning participant's id, used in admin
multi-participant fetches (e.g., the per-factor voice panel in the
analysis page).
 */
export interface ParticipantAudioRecording {
    question_key: string;
    mime_type: string;
    file_size_bytes: number;
    duration_seconds?: ParticipantAudioRecordingDurationSeconds;
    id: number;
    s3_key: string;
    created_at: string;
    presigned_url?: ParticipantAudioRecordingPresignedUrl;
    url_expires_at?: ParticipantAudioRecordingUrlExpiresAt;
    participant_db_id: number;
}
