/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { ParticipantStatus } from './participantStatus';
import type { ParticipantReadSubmittedAt } from './participantReadSubmittedAt';
import type { ParticipantReadDiscardReason } from './participantReadDiscardReason';
import type { ParticipantReadUserAgent } from './participantReadUserAgent';
import type { ParticipantReadLastStepReached } from './participantReadLastStepReached';
import type { ParticipantReadLastStepReachedAt } from './participantReadLastStepReachedAt';
import type { ParticipantReadRecruitmentToken } from './participantReadRecruitmentToken';

/**
 * Schema for reading a participant.
 */
export interface ParticipantRead {
    id: number;
    study_id: number;
    session_token: string;
    language_used: string;
    status: ParticipantStatus;
    created_at: string;
    submitted_at: ParticipantReadSubmittedAt;
    is_discarded: boolean;
    discard_reason: ParticipantReadDiscardReason;
    user_agent: ParticipantReadUserAgent;
    last_step_reached?: ParticipantReadLastStepReached;
    last_step_reached_at?: ParticipantReadLastStepReachedAt;
    recruitment_token?: ParticipantReadRecruitmentToken;
}
