/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * A single non-empty `card_comment` written by a participant during post-sort.

Returned by the analysis comments endpoint to support critical
Q-methodology interpretation: the analyst reads the textual rationales
of participants flagged on a given factor, alongside the audio recordings
already surfaced by `ParticipantAudioRecording` (Sneegas 2020;
Robbins & Krueger 2000).
 */
export interface ParticipantCardComment {
    participant_db_id: number;
    statement_id: number;
    statement_code: string;
    /** Statement text in the study's default language, with fallback to the first available translation, then to the code. */
    statement_text: string;
    grid_score: number;
    /** Non-empty textual rationale. */
    comment: string;
}
