/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * 1-indexed factor this participant is flagged to, or null
 */
export type ParticipantLoadingFlaggedFactor = number | null;
