/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */

export interface ParticipantBuckets {
    started: number;
    completed: number;
    discarded: number;
    test_runs: number;
    anonymised: number;
    total: number;
}
