/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { ParticipantStatus } from './participantStatus';
import type { ParticipantDetailReadSubmittedAt } from './participantDetailReadSubmittedAt';
import type { ParticipantDetailReadDiscardReason } from './participantDetailReadDiscardReason';
import type { ParticipantDetailReadUserAgent } from './participantDetailReadUserAgent';
import type { ParticipantDetailReadLastStepReached } from './participantDetailReadLastStepReached';
import type { ParticipantDetailReadLastStepReachedAt } from './participantDetailReadLastStepReachedAt';
import type { ParticipantDetailReadRecruitmentToken } from './participantDetailReadRecruitmentToken';
import type { ParticipantDetailReadPresortAnswers } from './participantDetailReadPresortAnswers';
import type { ParticipantDetailReadPostsortAnswers } from './participantDetailReadPostsortAnswers';
import type { QSortEntryRead } from './qSortEntryRead';
import type { AudioRecordingRead } from './audioRecordingRead';

/**
 * Schema for detailed participant view including responses.
 */
export interface ParticipantDetailRead {
    id: number;
    study_id: number;
    session_token: string;
    language_used: string;
    status: ParticipantStatus;
    created_at: string;
    submitted_at: ParticipantDetailReadSubmittedAt;
    is_discarded: boolean;
    discard_reason: ParticipantDetailReadDiscardReason;
    user_agent: ParticipantDetailReadUserAgent;
    last_step_reached?: ParticipantDetailReadLastStepReached;
    last_step_reached_at?: ParticipantDetailReadLastStepReachedAt;
    recruitment_token?: ParticipantDetailReadRecruitmentToken;
    presort_answers: ParticipantDetailReadPresortAnswers;
    postsort_answers: ParticipantDetailReadPostsortAnswers;
    qsort_entries: QSortEntryRead[];
    audio_recordings?: AudioRecordingRead[];
}
