/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { PartnerLogoUrl } from './partnerLogoUrl';

/**
 * Schema for a partner institution logo.
 */
export interface PartnerLogo {
    id: string;
    name: string;
    logo_url: string;
    url?: PartnerLogoUrl;
}
