/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { ParticipantDiscardUpdateDiscardReason } from './participantDiscardUpdateDiscardReason';

/**
 * Schema for discarding/flagging a participant.
 */
export interface ParticipantDiscardUpdate {
  is_discarded: boolean;
  discard_reason?: ParticipantDiscardUpdateDiscardReason;
}
