/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Factor loading for a single participant.
 */
export interface ParticipantLoading {
    db_id: number;
    label: string;
    loadings: number[];
    /** 1-indexed factors this participant is flagged to (may be multiple or empty) */
    flagged_factors?: number[];
}
