/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for changing password.
 */
export interface PasswordChange {
    current_password: string;
    /** @minLength 8 */
    new_password: string;
}
