/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for confirming a password reset via email-link JWT.
 */
export interface PasswordResetConfirm {
    token: string;
    /** @minLength 8 */
    new_password: string;
}
