/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

export type PreviewRangeRequestFlagging =
    (typeof PreviewRangeRequestFlagging)[keyof typeof PreviewRangeRequestFlagging];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PreviewRangeRequestFlagging = {
    auto: 'auto',
    manual: 'manual',
} as const;
