/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request body for POST /analysis/preview-range.
 */
export interface PreviewRangeRequest {
    /**
     * Candidate k values, e.g. [2, 3, 4, 5, 6].
     * @minItems 1
     * @maxItems 8
     */
    n_factors_range: number[];
    extraction?: string;
    rotation?: string;
    flagging?: string;
}
