/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * One PreviewSummary row, mirrors the service TypedDict.
 */
export interface PreviewRangeRow {
    n_factors: number;
    cumulative_variance: number;
    pct_flagged: number;
    n_distinguishing: number;
    n_cross_loaders: number;
    n_consensus: number;
    min_defining_sorts: number;
    has_empty_factor: boolean;
}
