/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { ProcessStepColor } from './processStepColor';

/**
 * Schema for a dynamic study process step.
 */
export interface ProcessStep {
    /** Unique ID for DND and tracking */
    id: string;
    /** @maxLength 100 */
    title: string;
    /** @maxLength 500 */
    description: string;
    /** Lucide icon name */
    icon: string;
    /** Hex color code or CSS variable */
    color?: ProcessStepColor;
}
