/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for recording participant step progress.
 */
export interface ProgressUpdate {
    session_token: string;
    /**
     * @minimum 1
     * @maximum 5
     */
    step: number;
}
