/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectRole } from './projectRole';

/**
 * Schema for updating a project member.
 */
export interface ProjectMemberUpdate {
    role: ProjectRole;
}
