/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectRole } from './projectRole';

/**
 * Schema for creating a project invitation.
 */
export interface ProjectInvitationCreate {
    email: string;
    role?: ProjectRole;
}
