/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectUpdateTitle } from './projectUpdateTitle';
import type { ProjectUpdateSlug } from './projectUpdateSlug';

/**
 * Schema for updating a project.
 */
export interface ProjectUpdate {
    title?: ProjectUpdateTitle;
    slug?: ProjectUpdateSlug;
}
