/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectMemberRead } from './projectMemberRead';
import type { QuotaInfo } from './quotaInfo';
import type { ProjectRole } from './projectRole';

/**
 * Schema for reading a project with the current user's role.
 */
export interface ProjectWithRole {
    id: number;
    title: string;
    slug: string;
    created_at: string;
    members?: ProjectMemberRead[];
    member_quota: QuotaInfo;
    user_role: ProjectRole;
}
