/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Enum for project roles.
 */
export type ProjectRole = (typeof ProjectRole)[keyof typeof ProjectRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectRole = {
    owner: 'owner',
    researcher: 'researcher',
    viewer: 'viewer',
} as const;
