/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for creating a project.
 */
export interface ProjectCreate {
    /** @maxLength 100 */
    title: string;
    /**
     * @minLength 3
     * @maxLength 50
     * @pattern ^[a-z0-9-]+$
     */
    slug: string;
}
