/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectMemberRead } from './projectMemberRead';

/**
 * Schema for reading a project with members.
 */
export interface ProjectRead {
    id: number;
    title: string;
    slug: string;
    created_at: string;
    members?: ProjectMemberRead[];
}
