/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Lightweight project schema (no members) for nested use in StudyRead.
 */
export interface ProjectBrief {
    id: number;
    title: string;
    slug: string;
    created_at: string;
}
