/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectMemberRead } from './projectMemberRead';
import type { QuotaInfo } from './quotaInfo';

/**
 * Schema for reading a project with members.
 */
export interface ProjectRead {
    id: number;
    title: string;
    slug: string;
    created_at: string;
    members?: ProjectMemberRead[];
    member_quota: QuotaInfo;
}
