/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { PublicConfigEmailDelivery } from './publicConfigEmailDelivery';

/**
 * Minimal client bootstrap payload.

``email_delivery`` is "smtp" when SMTP credentials are configured and
"manual" otherwise. When "manual", recovery links are generated by a
superuser from the admin UI rather than emailed (see
docs/guides/running-without-smtp.md).
 */
export interface PublicConfig {
    email_delivery: PublicConfigEmailDelivery;
}
