/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { QSortEntryInputCardComment } from './qSortEntryInputCardComment';

/**
 * Schema for individual statement placement during submission.
 */
export interface QSortEntryInput {
    statement_id: number;
    grid_score: number;
    card_comment?: QSortEntryInputCardComment;
}
