/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { QSortEntryReadCardComment } from './qSortEntryReadCardComment';

/**
 * Schema for reading individual statement placement.
 */
export interface QSortEntryRead {
    statement_id: number;
    grid_score: number;
    card_comment?: QSortEntryReadCardComment;
    statement_code: string;
}
