/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { QSortEntryInputCardComment } from './qSortEntryInputCardComment';

/**
 * Schema for individual statement placement during submission.
 */
export interface QSortEntryInput {
    statement_id: number;
    /**
     * @minimum -10
     * @maximum 10
     */
    grid_score: number;
    card_comment?: QSortEntryInputCardComment;
}
