/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { QuotaInfoLimit } from './quotaInfoLimit';

/**
 * Shared quota envelope used in member and owned-project counters.

`limit` is `None` when the quota is unlimited (operator opted out via
`0`-sentinel setting, or the requesting user is a superuser).
 */
export interface QuotaInfo {
    count: number;
    limit: QuotaInfoLimit;
}
