/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * A freshly-minted, never-persisted recovery link for out-of-band
delivery when SMTP is not configured.
 */
export interface RecoveryLinkResponse {
    kind: 'password_reset';
    url: string;
    expires_at: string;
}
