/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { RecruitmentLinkReadName } from './recruitmentLinkReadName';
import type { RecruitmentLinkType } from './recruitmentLinkType';
import type { RecruitmentLinkReadCapacity } from './recruitmentLinkReadCapacity';
import type { RecruitmentLinkReadExpiresAt } from './recruitmentLinkReadExpiresAt';

/**
 * Schema for reading a recruitment link.
 */
export interface RecruitmentLinkRead {
    name?: RecruitmentLinkReadName;
    type?: RecruitmentLinkType;
    capacity?: RecruitmentLinkReadCapacity;
    id: number;
    study_id: number;
    token: string;
    usage_count: number;
    start_count: number;
    expires_at?: RecruitmentLinkReadExpiresAt;
    is_active?: boolean;
    created_at: string;
}
