/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { RecruitmentLinkCreateName } from './recruitmentLinkCreateName';
import type { RecruitmentLinkType } from './recruitmentLinkType';
import type { RecruitmentLinkCreateCapacity } from './recruitmentLinkCreateCapacity';
import type { RecruitmentLinkCreateExpiresAt } from './recruitmentLinkCreateExpiresAt';

/**
 * Schema for creating a recruitment link.
 */
export interface RecruitmentLinkCreate {
    name?: RecruitmentLinkCreateName;
    type?: RecruitmentLinkType;
    capacity?: RecruitmentLinkCreateCapacity;
    expires_at?: RecruitmentLinkCreateExpiresAt;
    is_active?: boolean;
}
