/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */

/**
 * A single translation in a staleness diff.
 */
export interface StaleTranslation {
    language_code: string;
    text: string;
}
