/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { StatementTranslationCreate } from './statementTranslationCreate';

/**
 * Schema for creating a statement.
 */
export interface StatementCreate {
  code: string;
  translations: StatementTranslationCreate[];
}
