/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { StatementTranslationRead } from './statementTranslationRead';

/**
 * Schema for reading a statement.
 */
export interface StatementRead {
    /** @maxLength 50 */
    code: string;
    id: number;
    translations?: StatementTranslationRead[];
}
