/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Pairwise significance levels, e.g. {'1-2': 'p<0.05', '1-3': 'p<0.01'}
 */
export type StatementClassificationSignificance = { [key: string]: string };
