/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { StatementScoreZScoresItem } from './statementScoreZScoresItem';

/**
 * Z-scores and factor array values for a single statement.
 */
export interface StatementScore {
    statement_id: number;
    code: string;
    text: string;
    z_scores: StatementScoreZScoresItem[];
    factor_arrays: number[];
}
