/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { StatementTranslationCreate } from './statementTranslationCreate';

/**
 * Schema for creating a statement.
 */
export interface StatementCreate {
    /** @maxLength 50 */
    code: string;
    translations: StatementTranslationCreate[];
}
