/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { StatementTranslationRead } from './statementTranslationRead';
import type { StatementReadSourceConcourseItemId } from './statementReadSourceConcourseItemId';
import type { StatementReadSourceImportedAt } from './statementReadSourceImportedAt';

/**
 * Schema for reading a statement.
 */
export interface StatementRead {
    /** @maxLength 50 */
    code: string;
    id: number;
    display_order?: number;
    translations?: StatementTranslationRead[];
    source_concourse_item_id?: StatementReadSourceConcourseItemId;
    source_imported_at?: StatementReadSourceImportedAt;
}
