/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Z-scores and factor array values for a single statement.
 */
export interface StatementScore {
    statement_id: number;
    code: string;
    text: string;
    z_scores: number[];
    factor_arrays: number[];
}
