/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Enum for study lifecycle states.
 */
export type StudyState = typeof StudyState[keyof typeof StudyState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StudyState = {
  draft: 'draft',
  active: 'active',
  paused: 'paused',
  closed: 'closed',
  archived: 'archived',
} as const;
