/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { StudyState } from './studyState';
import type { GridColumn } from './gridColumn';
import type { StudyReadPresortConfig } from './studyReadPresortConfig';
import type { StudyReadPostsortConfig } from './studyReadPostsortConfig';
import type { StudyReadDefaultLanguage } from './studyReadDefaultLanguage';
import type { StudyTranslationRead } from './studyTranslationRead';
import type { StatementRead } from './statementRead';

/**
 * Schema for reading a study.
 */
export interface StudyRead {
    /**
     * @minLength 3
     * @maxLength 100
     * @pattern ^[a-z0-9-]+$
     */
    slug: string;
    state?: StudyState;
    grid_config: GridColumn[];
    presort_config: StudyReadPresortConfig;
    postsort_config: StudyReadPostsortConfig;
    default_language?: StudyReadDefaultLanguage;
    show_statement_codes?: boolean;
    id: number;
    workspace_id: number;
    created_at: string;
    translations?: StudyTranslationRead[];
    statements?: StatementRead[];
}
