/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { StudyState } from './studyState';
import type { GridColumn } from './gridColumn';
import type { StudyReadPresortConfig } from './studyReadPresortConfig';
import type { StudyReadPostsortConfig } from './studyReadPostsortConfig';
import type { StudyReadBranding } from './studyReadBranding';
import type { StudyReadDefaultLanguage } from './studyReadDefaultLanguage';
import type { StudyReadStartDate } from './studyReadStartDate';
import type { StudyReadEndDate } from './studyReadEndDate';
import type { StudyReadWorkspace } from './studyReadWorkspace';
import type { StudyTranslationRead } from './studyTranslationRead';
import type { StatementRead } from './statementRead';
import type { RecruitmentLinkRead } from './recruitmentLinkRead';

/**
 * Schema for reading a study.
 */
export interface StudyRead {
    /**
     * @minLength 3
     * @maxLength 100
     * @pattern ^[a-z0-9-]+$
     */
    slug: string;
    state?: StudyState;
    grid_config: GridColumn[];
    presort_config: StudyReadPresortConfig;
    postsort_config: StudyReadPostsortConfig;
    branding?: StudyReadBranding;
    default_language?: StudyReadDefaultLanguage;
    show_statement_codes?: boolean;
    randomize_statement_order?: boolean;
    symmetry_lock?: boolean;
    start_date?: StudyReadStartDate;
    end_date?: StudyReadEndDate;
    id: number;
    workspace_id: number;
    workspace?: StudyReadWorkspace;
    created_at: string;
    updated_at: string;
    translations?: StudyTranslationRead[];
    statements?: StatementRead[];
    recruitment_links?: RecruitmentLinkRead[];
    requires_password?: boolean;
}
