/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { StudyTranslationCreateInstructions } from './studyTranslationCreateInstructions';
import type { StudyTranslationCreateSubtitle } from './studyTranslationCreateSubtitle';
import type { StudyTranslationCreateObjective } from './studyTranslationCreateObjective';
import type { StudyTranslationCreateConditionOfInstruction } from './studyTranslationCreateConditionOfInstruction';
import type { StudyTranslationCreateConsentTitle } from './studyTranslationCreateConsentTitle';
import type { StudyTranslationCreateConsentDescription } from './studyTranslationCreateConsentDescription';
import type { StudyTranslationCreateUiLabels } from './studyTranslationCreateUiLabels';
import type { ProcessStep } from './processStep';
import type { StudyTranslationCreateStepHelp } from './studyTranslationCreateStepHelp';

/**
 * Schema for creating a study translation.
 */
export interface StudyTranslationCreate {
    /**
     * @maxLength 5
     * @pattern ^[a-z]{2}(-[A-Z]{2})?$
     */
    language_code: string;
    /** @maxLength 200 */
    title: string;
    /** @maxLength 2000 */
    description?: string;
    instructions?: StudyTranslationCreateInstructions;
    subtitle?: StudyTranslationCreateSubtitle;
    objective?: StudyTranslationCreateObjective;
    condition_of_instruction?: StudyTranslationCreateConditionOfInstruction;
    consent_title?: StudyTranslationCreateConsentTitle;
    consent_description?: StudyTranslationCreateConsentDescription;
    ui_labels?: StudyTranslationCreateUiLabels;
    process_steps?: ProcessStep[];
    methodology_tips?: string[];
    step_help?: StudyTranslationCreateStepHelp;
}
