/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { StudyTranslationReadSubtitle } from './studyTranslationReadSubtitle';
import type { StudyTranslationReadObjective } from './studyTranslationReadObjective';
import type { StudyTranslationReadConsentTitle } from './studyTranslationReadConsentTitle';
import type { StudyTranslationReadConsentDescription } from './studyTranslationReadConsentDescription';
import type { StudyTranslationReadConsentAccept } from './studyTranslationReadConsentAccept';
import type { StudyTranslationReadConsentDecline } from './studyTranslationReadConsentDecline';
import type { StudyTranslationReadUiLabels } from './studyTranslationReadUiLabels';

/**
 * Schema for reading a study translation.
 */
export interface StudyTranslationRead {
    /**
     * @maxLength 5
     * @pattern ^[a-z]{2}(-[A-Z]{2})?$
     */
    language_code: string;
    /**
     * @minLength 1
     * @maxLength 200
     */
    title: string;
    description?: string;
    instructions?: string;
    subtitle?: StudyTranslationReadSubtitle;
    objective?: StudyTranslationReadObjective;
    consent_title?: StudyTranslationReadConsentTitle;
    consent_description?: StudyTranslationReadConsentDescription;
    consent_accept?: StudyTranslationReadConsentAccept;
    consent_decline?: StudyTranslationReadConsentDecline;
    ui_labels?: StudyTranslationReadUiLabels;
    id: number;
    study_id: number;
}
