/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { StudyState } from './studyState';
import type { GridColumn } from './gridColumn';
import type { StudyCreatePresortConfig } from './studyCreatePresortConfig';
import type { StudyCreatePostsortConfig } from './studyCreatePostsortConfig';
import type { StudyCreateBranding } from './studyCreateBranding';
import type { StudyCreateDefaultLanguage } from './studyCreateDefaultLanguage';
import type { StudyCreateStartDate } from './studyCreateStartDate';
import type { StudyCreateEndDate } from './studyCreateEndDate';
import type { StudyTranslationCreate } from './studyTranslationCreate';
import type { StatementCreate } from './statementCreate';

/**
 * Schema for creating a study.
 */
export interface StudyCreate {
    /**
     * @minLength 3
     * @maxLength 100
     * @pattern ^[a-z0-9-]+$
     */
    slug: string;
    state?: StudyState;
    grid_config: GridColumn[];
    presort_config: StudyCreatePresortConfig;
    postsort_config: StudyCreatePostsortConfig;
    branding?: StudyCreateBranding;
    default_language?: StudyCreateDefaultLanguage;
    show_statement_codes?: boolean;
    randomize_statement_order?: boolean;
    symmetry_lock?: boolean;
    start_date?: StudyCreateStartDate;
    end_date?: StudyCreateEndDate;
    translations: StudyTranslationCreate[];
    statements?: StatementCreate[];
}
