/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { StudyState } from './studyState';

export type StudyUpdateState = StudyState | null;
