/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { StudyTranslationCreateSubtitle } from './studyTranslationCreateSubtitle';
import type { StudyTranslationCreateObjective } from './studyTranslationCreateObjective';
import type { StudyTranslationCreateConsentTitle } from './studyTranslationCreateConsentTitle';
import type { StudyTranslationCreateConsentDescription } from './studyTranslationCreateConsentDescription';
import type { StudyTranslationCreateConsentAccept } from './studyTranslationCreateConsentAccept';
import type { StudyTranslationCreateConsentDecline } from './studyTranslationCreateConsentDecline';
import type { StudyTranslationCreateUiLabels } from './studyTranslationCreateUiLabels';

/**
 * Schema for creating a study translation.
 */
export interface StudyTranslationCreate {
  /**
   * @maxLength 5
   * @pattern ^[a-z]{2}(-[A-Z]{2})?$
   */
  language_code: string;
  /**
   * @minLength 1
   * @maxLength 200
   */
  title: string;
  description?: string;
  instructions?: string;
  subtitle?: StudyTranslationCreateSubtitle;
  objective?: StudyTranslationCreateObjective;
  consent_title?: StudyTranslationCreateConsentTitle;
  consent_description?: StudyTranslationCreateConsentDescription;
  consent_accept?: StudyTranslationCreateConsentAccept;
  consent_decline?: StudyTranslationCreateConsentDecline;
  ui_labels?: StudyTranslationCreateUiLabels;
}
