/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { StudyUpdateSlug } from './studyUpdateSlug';
import type { StudyUpdateState } from './studyUpdateState';
import type { StudyUpdateGridConfig } from './studyUpdateGridConfig';
import type { StudyUpdatePresortConfig } from './studyUpdatePresortConfig';
import type { StudyUpdatePostsortConfig } from './studyUpdatePostsortConfig';
import type { StudyUpdateDefaultLanguage } from './studyUpdateDefaultLanguage';
import type { StudyUpdateShowStatementCodes } from './studyUpdateShowStatementCodes';
import type { StudyUpdateTranslations } from './studyUpdateTranslations';
import type { StudyUpdateStatements } from './studyUpdateStatements';

/**
 * Schema for updating a study.
 */
export interface StudyUpdate {
    slug?: StudyUpdateSlug;
    state?: StudyUpdateState;
    grid_config?: StudyUpdateGridConfig;
    presort_config?: StudyUpdatePresortConfig;
    postsort_config?: StudyUpdatePostsortConfig;
    default_language?: StudyUpdateDefaultLanguage;
    show_statement_codes?: StudyUpdateShowStatementCodes;
    translations?: StudyUpdateTranslations;
    statements?: StudyUpdateStatements;
}
