/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { StudyStatsReadMedianDurationSeconds } from './studyStatsReadMedianDurationSeconds';
import type { StudyStatsReadDeviceBreakdown } from './studyStatsReadDeviceBreakdown';

/**
 * Schema for study statistics.
 */
export interface StudyStatsRead {
    started_count: number;
    completed_count: number;
    completion_rate: number;
    median_duration_seconds: StudyStatsReadMedianDurationSeconds;
    device_breakdown: StudyStatsReadDeviceBreakdown;
}
