/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { StudyDumpResponseStudy } from './studyDumpResponseStudy';
import type { StudyDumpResponseParticipantsItem } from './studyDumpResponseParticipantsItem';
import type { StudyDumpResponseStatementIdToIndex } from './studyDumpResponseStatementIdToIndex';

/**
 * Admin full-study dump (GET /admin/studies/{slug}/dump).

Open shape — the runtime payload is the StudyDump TypedDict from
`app.types.wire`: `{study, participants, statement_id_to_index}`. We
declare the well-known top-level keys as `dict` / `list` and accept
additional keys via `extra='allow'` so orval emits a named interface
rather than an opaque dict.
 */
export interface StudyDumpResponse {
    study: StudyDumpResponseStudy;
    participants: StudyDumpResponseParticipantsItem[];
    statement_id_to_index: StudyDumpResponseStatementIdToIndex;
    [key: string]: unknown;
}
