/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */

export type StudyRole = (typeof StudyRole)[keyof typeof StudyRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StudyRole = {
    owner: 'owner',
    editor: 'editor',
    viewer: 'viewer',
} as const;
