/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { StudyState } from './studyState';
import type { GridColumn } from './gridColumn';
import type { StudyCreatePresortConfig } from './studyCreatePresortConfig';
import type { StudyCreatePostsortConfig } from './studyCreatePostsortConfig';
import type { StudyCreateDefaultLanguage } from './studyCreateDefaultLanguage';
import type { StudyTranslationCreate } from './studyTranslationCreate';
import type { StatementCreate } from './statementCreate';

/**
 * Schema for creating a study.
 */
export interface StudyCreate {
    /**
     * @minLength 3
     * @maxLength 100
     * @pattern ^[a-z0-9-]+$
     */
    slug: string;
    state?: StudyState;
    grid_config: GridColumn[];
    presort_config: StudyCreatePresortConfig;
    postsort_config: StudyCreatePostsortConfig;
    default_language?: StudyCreateDefaultLanguage;
    show_statement_codes?: boolean;
    translations: StudyTranslationCreate[];
    statements?: StatementCreate[];
}
