/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { StatementUpdate } from './statementUpdate';

export type StudyUpdateStatements = StatementUpdate[] | null;
