/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { WorkspaceRead } from './workspaceRead';

export type StudyReadWorkspace = WorkspaceRead | null;
