/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { SubmissionInputPresortAnswersAnyOf } from './submissionInputPresortAnswersAnyOf';

export type SubmissionInputPresortAnswers = SubmissionInputPresortAnswersAnyOf | null;
