/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { SubmissionInputPostsortAnswersAnyOf } from './submissionInputPostsortAnswersAnyOf';

export type SubmissionInputPostsortAnswers = SubmissionInputPostsortAnswersAnyOf | null;
