/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { TimelineSnapshotFirstSubmissionAt } from './timelineSnapshotFirstSubmissionAt';
import type { TimelineSnapshotLastSubmissionAt } from './timelineSnapshotLastSubmissionAt';
import type { TimelineSnapshotLastAnonymisationAt } from './timelineSnapshotLastAnonymisationAt';

export interface TimelineSnapshot {
    first_submission_at: TimelineSnapshotFirstSubmissionAt;
    last_submission_at: TimelineSnapshotLastSubmissionAt;
    last_anonymisation_at: TimelineSnapshotLastAnonymisationAt;
    /** Completed participants whose submitted_at is more than 1 year ago */
    completed_older_than_1y: number;
    /** Completed participants whose submitted_at is more than 2 years ago */
    completed_older_than_2y: number;
}
