/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { TokenAccessToken } from './tokenAccessToken';
import type { TokenTokenType } from './tokenTokenType';
import type { TokenTempToken } from './tokenTempToken';

/**
 * Schema for returning an access token or 2FA requirement.

`requires_2fa=True` (with no access token) signals the frontend to
prompt for the authenticator-app code; a successful response carries
the access token instead.
 */
export interface Token {
    access_token?: TokenAccessToken;
    token_type?: TokenTokenType;
    requires_2fa?: boolean;
    temp_token?: TokenTempToken;
}
