/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for returning an access token.
 */
export interface Token {
  access_token: string;
  token_type: string;
}
