/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for TOTP setup response.
 */
export interface TOTPSetup {
    secret: string;
    qr_code_uri: string;
}
