/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

export type TwoFAEnableRequestChannel =
    (typeof TwoFAEnableRequestChannel)[keyof typeof TwoFAEnableRequestChannel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TwoFAEnableRequestChannel = {
    app: 'app',
    email: 'email',
} as const;
