/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for reading user details.
 */
export interface UserRead {
    email: string;
    id: number;
    is_active: boolean;
    is_superuser: boolean;
}
