/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { UserReadAdminFullName } from './userReadAdminFullName';
import type { UserReadAdminPendingEmail } from './userReadAdminPendingEmail';
import type { UserReadAdminOwnedProjectQuota } from './userReadAdminOwnedProjectQuota';
import type { UserReadAdminEmailVerifiedAt } from './userReadAdminEmailVerifiedAt';
import type { UserReadAdminLastLoginAt } from './userReadAdminLastLoginAt';

/**
 * Extended user read schema for superuser-only admin endpoints.

Carries audit fields that we do NOT expose on the public /api/me path:
superusers see them so they can audit account hygiene
(last login, password age, email verification status).
 */
export interface UserReadAdmin {
    email: string;
    full_name?: UserReadAdminFullName;
    id: number;
    is_active: boolean;
    is_superuser: boolean;
    is_totp_enabled: boolean;
    pending_email?: UserReadAdminPendingEmail;
    owned_project_quota?: UserReadAdminOwnedProjectQuota;
    email_verified_at?: UserReadAdminEmailVerifiedAt;
    password_changed_at: string;
    last_login_at?: UserReadAdminLastLoginAt;
}
