/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { UserRead } from './userRead';

/**
 * Response from POST /api/register: the user + a verification flag.
 */
export interface UserCreateResponse {
    user: UserRead;
    requires_email_verification: boolean;
}
