/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { UserAdminUpdateIsActive } from './userAdminUpdateIsActive';
import type { UserAdminUpdateIsSuperuser } from './userAdminUpdateIsSuperuser';
import type { UserAdminUpdateFullName } from './userAdminUpdateFullName';

/**
 * PATCH payload for /api/admin/users/{id}.

Each field is optional so superusers can change one flag at a time
(e.g. demote without touching activation status). Email and password
are deliberately absent: email goes through the user-driven
/me email-change flow; password goes through force-password-reset.
 */
export interface UserAdminUpdate {
    is_active?: UserAdminUpdateIsActive;
    is_superuser?: UserAdminUpdateIsSuperuser;
    full_name?: UserAdminUpdateFullName;
}
