/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { UserCreateFullName } from './userCreateFullName';
import type { UserCreateInvitationToken } from './userCreateInvitationToken';

/**
 * Schema for creating a new user.
 */
export interface UserCreate {
    email: string;
    full_name?: UserCreateFullName;
    /** @minLength 8 */
    password: string;
    is_active?: boolean;
    is_superuser?: boolean;
    invitation_token?: UserCreateInvitationToken;
}
