/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { UserUpdateEmail } from './userUpdateEmail';
import type { UserUpdateFullName } from './userUpdateFullName';

/**
 * Schema for updating user profile.
 */
export interface UserUpdate {
    email?: UserUpdateEmail;
    full_name?: UserUpdateFullName;
}
