/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { UserCreateInvitationToken } from './userCreateInvitationToken';

/**
 * Schema for creating a new user.
 */
export interface UserCreate {
  email: string;
  password: string;
  is_active?: boolean;
  is_superuser?: boolean;
  invitation_token?: UserCreateInvitationToken;
}
