/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { ValidationResultSummary } from './validationResultSummary';

export interface ValidationResult {
    valid: boolean;
    errors: string[];
    warnings: string[];
    summary?: ValidationResultSummary;
}
