/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { ValidationSummary } from './validationSummary';

export type ValidationResultSummary = ValidationSummary | null;
