/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { WorkspaceRole } from './workspaceRole';

/**
 * Schema for creating a workspace invitation.
 */
export interface WorkspaceInvitationCreate {
    email: string;
    role?: WorkspaceRole;
}
