/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Enum for workspace roles.
 */
export type WorkspaceRole = (typeof WorkspaceRole)[keyof typeof WorkspaceRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkspaceRole = {
    admin: 'admin',
    researcher: 'researcher',
    viewer: 'viewer',
} as const;
