/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { WorkspaceMemberRead } from './workspaceMemberRead';
import type { WorkspaceRole } from './workspaceRole';

/**
 * Schema for reading a workspace with the current user's role.
 */
export interface WorkspaceWithRole {
    id: number;
    title: string;
    slug: string;
    created_at: string;
    members?: WorkspaceMemberRead[];
    user_role: WorkspaceRole;
}
