/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Lightweight workspace schema (no members) for nested use in StudyRead.
 */
export interface WorkspaceBrief {
    id: number;
    title: string;
    slug: string;
    created_at: string;
}
