/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { WorkspaceMemberRead } from './workspaceMemberRead';

/**
 * Schema for reading a workspace.
 */
export interface WorkspaceRead {
    id: number;
    title: string;
    slug: string;
    created_at: string;
    members?: WorkspaceMemberRead[];
}
