/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { WorkspaceMemberReadUserEmail } from './workspaceMemberReadUserEmail';
import type { WorkspaceRole } from './workspaceRole';

/**
 * Schema for reading workspace member details.
 */
export interface WorkspaceMemberRead {
    user_id: number;
    user_email?: WorkspaceMemberReadUserEmail;
    role: WorkspaceRole;
    joined_at: string;
}
