/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { WorkspaceRole } from './workspaceRole';

/**
 * Schema for updating a workspace member.
 */
export interface WorkspaceMemberUpdate {
    role: WorkspaceRole;
}
