/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Enum for workspace roles.
 */
export type WorkspaceRole = (typeof WorkspaceRole)[keyof typeof WorkspaceRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkspaceRole = {
    owner: 'owner',
    researcher: 'researcher',
    viewer: 'viewer',
} as const;
