/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { WorkspaceUpdateTitle } from './workspaceUpdateTitle';
import type { WorkspaceUpdateSlug } from './workspaceUpdateSlug';

/**
 * Schema for updating a workspace.
 */
export interface WorkspaceUpdate {
    title?: WorkspaceUpdateTitle;
    slug?: WorkspaceUpdateSlug;
}
