"""Public bootstrap config exposed unauthenticated at GET /api/config."""

from typing import Literal

from pydantic import BaseModel


class PublicConfig(BaseModel):
    """Minimal client bootstrap payload.

    ``email_delivery`` is "smtp" when SMTP credentials are configured and
    "manual" otherwise. When "manual", recovery links are generated by a
    superuser from the admin UI rather than emailed (see
    docs/guides/running-without-smtp.md).
    """

    email_delivery: Literal["smtp", "manual"]
