"""Add audio_recordings table

Revision ID: 2bf0f513c6c8
Revises: a64b4724fcb8
Create Date: 2026-02-08 22:24:56.046123

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2bf0f513c6c8"
down_revision: Union[str, Sequence[str], None] = "a64b4724fcb8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("totp_secret", sa.String(), nullable=True),
        sa.Column("is_totp_enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "workspaces",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workspaces_id"), "workspaces", ["id"], unique=False)
    op.create_index(op.f("ix_workspaces_slug"), "workspaces", ["slug"], unique=True)
    op.create_table(
        "studies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "draft", "active", "paused", "closed", "archived", name="studystate"
            ),
            nullable=False,
        ),
        sa.Column("default_language", sa.String(length=5), nullable=True),
        sa.Column("show_statement_codes", sa.Boolean(), nullable=False),
        sa.Column("randomize_statement_order", sa.Boolean(), nullable=False),
        sa.Column("symmetry_lock", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("grid_config", sa.JSON(), nullable=False),
        sa.Column("presort_config", sa.JSON(), nullable=False),
        sa.Column("postsort_config", sa.JSON(), nullable=False),
        sa.Column("branding", sa.JSON(), nullable=True),
        sa.Column("access_password", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_studies_id"), "studies", ["id"], unique=False)
    op.create_index(op.f("ix_studies_slug"), "studies", ["slug"], unique=True)
    op.create_table(
        "workspace_members",
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("owner", "researcher", "viewer", name="workspacerole"),
            nullable=False,
        ),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("workspace_id", "user_id"),
    )
    op.create_table(
        "invitations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("study_id", sa.Integer(), nullable=True),
        sa.Column(
            "role",
            sa.Enum("owner", "researcher", "viewer", name="workspacerole"),
            nullable=False,
        ),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["study_id"], ["studies.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_invitations_email"), "invitations", ["email"], unique=False
    )
    op.create_index(op.f("ix_invitations_id"), "invitations", ["id"], unique=False)
    op.create_index(op.f("ix_invitations_token"), "invitations", ["token"], unique=True)
    op.create_index(
        op.f("ix_invitations_workspace_id"),
        "invitations",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "participants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("study_id", sa.Integer(), nullable=False),
        sa.Column("session_token", sa.Uuid(), nullable=False),
        sa.Column("language_used", sa.String(length=5), nullable=False),
        sa.Column("random_seed", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("started", "completed", name="participantstatus"),
            nullable=False,
        ),
        sa.Column("confirmation_code", sa.String(length=8), nullable=True),
        sa.Column("is_discarded", sa.Boolean(), nullable=False),
        sa.Column("is_test_run", sa.Boolean(), nullable=False),
        sa.Column("discard_reason", sa.String(), nullable=True),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consented_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consent_hash", sa.String(), nullable=True),
        sa.Column("presort_answers", sa.JSON(), nullable=False),
        sa.Column("postsort_answers", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["study_id"], ["studies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_participants_confirmation_code"),
        "participants",
        ["confirmation_code"],
        unique=True,
    )
    op.create_index(op.f("ix_participants_id"), "participants", ["id"], unique=False)
    op.create_index(
        op.f("ix_participants_session_token"),
        "participants",
        ["session_token"],
        unique=True,
    )
    op.create_index(
        op.f("ix_participants_study_id"), "participants", ["study_id"], unique=False
    )
    op.create_table(
        "recruitment_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("study_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("public", "individual", "limited", name="recruitmentlinktype"),
            nullable=False,
        ),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("start_count", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["study_id"], ["studies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recruitment_links_id"), "recruitment_links", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_recruitment_links_study_id"),
        "recruitment_links",
        ["study_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recruitment_links_token"), "recruitment_links", ["token"], unique=True
    )
    op.create_table(
        "statements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("study_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["study_id"], ["studies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("study_id", "code", name="uq_statement_code"),
    )
    op.create_index(op.f("ix_statements_id"), "statements", ["id"], unique=False)
    op.create_index(
        op.f("ix_statements_study_id"), "statements", ["study_id"], unique=False
    )
    op.create_table(
        "study_translations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("study_id", sa.Integer(), nullable=False),
        sa.Column("language_code", sa.String(length=5), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("subtitle", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("objective", sa.String(), nullable=True),
        sa.Column("condition_of_instruction", sa.String(), nullable=True),
        sa.Column("pre_instruction", sa.String(), nullable=True),
        sa.Column("instructions", sa.String(), nullable=True),
        sa.Column("ui_labels", sa.JSON(), nullable=False),
        sa.Column("consent_title", sa.String(), nullable=True),
        sa.Column("consent_description", sa.String(), nullable=True),
        sa.Column("process_steps", sa.JSON(), nullable=False),
        sa.Column("methodology_tips", sa.JSON(), nullable=False),
        sa.Column("step_help", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["study_id"], ["studies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("study_id", "language_code", name="uq_study_lang"),
    )
    op.create_index(
        op.f("ix_study_translations_id"), "study_translations", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_study_translations_study_id"),
        "study_translations",
        ["study_id"],
        unique=False,
    )
    op.create_table(
        "audio_recordings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("participant_id", sa.Integer(), nullable=False),
        sa.Column("question_key", sa.String(), nullable=False),
        sa.Column("s3_bucket", sa.String(), nullable=False),
        sa.Column("s3_key", sa.String(), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("mime_type", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"], ["participants.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "participant_id", "question_key", name="uq_participant_question_audio"
        ),
    )
    op.create_index(
        op.f("ix_audio_recordings_id"), "audio_recordings", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_audio_recordings_participant_id"),
        "audio_recordings",
        ["participant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audio_recordings_s3_key"), "audio_recordings", ["s3_key"], unique=True
    )
    op.create_table(
        "qsort_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("participant_id", sa.Integer(), nullable=False),
        sa.Column("statement_id", sa.Integer(), nullable=False),
        sa.Column("grid_score", sa.Integer(), nullable=False),
        sa.Column("card_comment", sa.String(), nullable=True),
        sa.CheckConstraint(
            "grid_score >= -10 AND grid_score <= 10", name="chk_grid_score_range"
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"], ["participants.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["statement_id"], ["statements.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "participant_id", "statement_id", name="uq_participant_statement"
        ),
    )
    op.create_index(op.f("ix_qsort_entries_id"), "qsort_entries", ["id"], unique=False)
    op.create_index(
        op.f("ix_qsort_entries_participant_id"),
        "qsort_entries",
        ["participant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_qsort_entries_statement_id"),
        "qsort_entries",
        ["statement_id"],
        unique=False,
    )
    op.create_table(
        "statement_translations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("statement_id", sa.Integer(), nullable=False),
        sa.Column("language_code", sa.String(length=5), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["statement_id"], ["statements.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("statement_id", "language_code", name="uq_statement_lang"),
    )
    op.create_index(
        op.f("ix_statement_translations_id"),
        "statement_translations",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_statement_translations_statement_id"),
        "statement_translations",
        ["statement_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_statement_translations_statement_id"),
        table_name="statement_translations",
    )
    op.drop_index(
        op.f("ix_statement_translations_id"), table_name="statement_translations"
    )
    op.drop_table("statement_translations")
    op.drop_index(op.f("ix_qsort_entries_statement_id"), table_name="qsort_entries")
    op.drop_index(op.f("ix_qsort_entries_participant_id"), table_name="qsort_entries")
    op.drop_index(op.f("ix_qsort_entries_id"), table_name="qsort_entries")
    op.drop_table("qsort_entries")
    op.drop_index(op.f("ix_audio_recordings_s3_key"), table_name="audio_recordings")
    op.drop_index(
        op.f("ix_audio_recordings_participant_id"), table_name="audio_recordings"
    )
    op.drop_index(op.f("ix_audio_recordings_id"), table_name="audio_recordings")
    op.drop_table("audio_recordings")
    op.drop_index(
        op.f("ix_study_translations_study_id"), table_name="study_translations"
    )
    op.drop_index(op.f("ix_study_translations_id"), table_name="study_translations")
    op.drop_table("study_translations")
    op.drop_index(op.f("ix_statements_study_id"), table_name="statements")
    op.drop_index(op.f("ix_statements_id"), table_name="statements")
    op.drop_table("statements")
    op.drop_index(op.f("ix_recruitment_links_token"), table_name="recruitment_links")
    op.drop_index(op.f("ix_recruitment_links_study_id"), table_name="recruitment_links")
    op.drop_index(op.f("ix_recruitment_links_id"), table_name="recruitment_links")
    op.drop_table("recruitment_links")
    op.drop_index(op.f("ix_participants_study_id"), table_name="participants")
    op.drop_index(op.f("ix_participants_session_token"), table_name="participants")
    op.drop_index(op.f("ix_participants_id"), table_name="participants")
    op.drop_index(op.f("ix_participants_confirmation_code"), table_name="participants")
    op.drop_table("participants")
    op.drop_index(op.f("ix_invitations_workspace_id"), table_name="invitations")
    op.drop_index(op.f("ix_invitations_token"), table_name="invitations")
    op.drop_index(op.f("ix_invitations_id"), table_name="invitations")
    op.drop_index(op.f("ix_invitations_email"), table_name="invitations")
    op.drop_table("invitations")
    op.drop_table("workspace_members")
    op.drop_index(op.f("ix_studies_slug"), table_name="studies")
    op.drop_index(op.f("ix_studies_id"), table_name="studies")
    op.drop_table("studies")
    op.drop_index(op.f("ix_workspaces_slug"), table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_id"), table_name="workspaces")
    op.drop_table("workspaces")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
