"""add is_test_run to participants

Revision ID: a64b4724fcb8
Revises: d3221972445d
Create Date: 2026-01-19 08:23:49.138429

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a64b4724fcb8"
down_revision: Union[str, Sequence[str], None] = "d3221972445d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "participants", sa.Column("is_test_run", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("participants", "is_test_run")
    # ### end Alembic commands ###
